### PR TITLE
[12.0][MIG] project_key

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@tarteo @pnajman-modoolar I'd like to request a review if you don't mind

**Review by pnajman-modoolar — APPROVED** [review]
Approved :)

**Review by tarteo — APPROVED** [review]
Looks good to me, thanks! Also tested it on Runbot

**Review by nikul-serpentcs — APPROVED** [review]
Code Review LGTM

**Pull request merged**
