### PR TITLE
[15.0][ADD] project_task_milestone: added module

### PR DESCRIPTION
**Pull request by Mantux11**
Added new module `project_task_milestone`. In odoo 15, `project_milestone` is by default. So this module would link `project_task` with `project_milestone` models.

IMPORTANT:

Migration to 15.0 `project_milestone`, migration scripts would be needed by migrating `project_milestone`  module. I'll do that later.

Discussion was here:  [discussion](https://github.com/OCA/project/issues/859).

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by yankinmax** [comment]
@Mantux11 @gurneyalex can we get this PR merged? Can I help somehow? Tests run without issues locally.

**Comment by Mantux11** [comment]
@yankinmax I couldn't see what's wrong with merging. I see that only` codecov` shows the error's and also here in PR, all checks has been successful except for `runbot` that it's not used anymore because of `runboat`. So I can't find where is the problem.

**Comment by yankinmax** [comment]
@Mantux11 yep, exactly! For me the same!
@gurneyalex could we somehow bypass runbot to merge this PR?

**Comment by Mantux11** [comment]
@davejames Hey. I saw that you migrated `project_milestone` module, because of that, I wanted your approve and want to "move" this and also `project_milestone` PR. Could you do that?

**Comment by Du-ma** [comment]
@gurneyalex 
Yo, can we merge this?

**Review by Du-ma — APPROVED** [review]

**Review by gaikaz — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Comment by alexey-pelykh** [comment]
@Mantux11 I can't really perform functional test, runboat is missing - maybe try to rebase onto 15.0 again and push?

**Comment by Mantux11** [comment]
@alexey-pelykh Done. Now runboat is accessible.

**Review by HaraldPanten — APPROVED** [review]

**Comment by Mantux11** [comment]
@alexey-pelykh Can you test and merge that? Later runboat would be inactive again.  Thanks :)

**Pull request merged**
