### PR TITLE
[16.0][MIG] project_stage_mgmt: Migration to version 16.0

### PR DESCRIPTION
**Pull request by NICO-SOLUTIONS**
standard migration

### CODE REVIEW

**Comment by NICO-SOLUTIONS** [comment]
@DavidJForgeFlow @MiquelRForgeFlow @mymage 
This is standard miration. In order to avoid misunderstanding, maybe renaming the module to project_task_stage_mgmt seems helpful. Just to separate it more clearly from the project-stages if enabled. I like the tool for managing stages during creation of a project and for better management for exisitng projects.

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM, also the improvements and the refactor seems a good idea IMO!

**Comment by NICO-SOLUTIONS** [comment]
@DavidJForgeFlow 
can i include the refactoring to the MIG commit? or better to separate them?

**Comment by DavidJForgeFlow** [comment]
I prefer to split in two commits, this way everyone will be able to simply check the migration or the refactor

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, makes sense :+1:

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
