### PR TITLE
[10.0][MIG] project_stage_closed

### PR DESCRIPTION
**Pull request by luismontalba**
Project Task Stage Closed
=====================

This module provides a 'closed' flag on project task stages.

Usage
--------

To use this module, you need to:

* Have Manager rights for Project group.
* Go to *Project > Configuration > Stages*.
* You have the "Closed" flag available to be checked on the form view.

cc @Tecnativa

### CODE REVIEW

**Review by dreispt — CHANGES_REQUESTED** [review]
Fix the [unused import](https://travis-ci.org/OCA/project/jobs/228749177#L508) and it's good to go!

**Review by pedrobaeza — APPROVED** [review]
Squash together both "OCA transbot" commit using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests and fix the linter error as said by Daniel, but it's correct.

**Comment by luismontalba** [comment]
Changes are done, but in this case I squashed it with my commit, sorry for that !

**Review by dreispt — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I merge this one as it's very straight-forward and it's required for other PRs.

**Pull request merged**
