### PR TITLE
10-mig project_task_department

### PR DESCRIPTION
**Pull request by thinkwelltwd**
The #173 PR hasn't been merged yet, but I need the module for v10. Hope you can use this PR for that

Depends on:
- [ ] #253

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Hi @thinkwelltwd Would you attend to the failing checks in this PR? I checked the code and I think It looks nice :cool:

**Comment by thinkwelltwd** [comment]
> Would you attend to the failing checks in this PR

I made a lint fix, but the tests are failing because `project_department` isn't available in the test environment.

**Comment by thinkwelltwd** [comment]
Could somebody add the `project_department` module to the test runner?

**Comment by dreispt** [comment]
We need to merge #253 and then rebase this PR.
Then the `project_department` won't be missing any more.

**Comment by thinkwelltwd** [comment]
> We need to merge #253 and then rebase this PR.

#253 is merged now. What about the rebasing? Is that something you want me to do?

**Pull request closed without merging**
