### PR TITLE
[13.0][IMP] project_status: Add multi-company support

### PR DESCRIPTION
**Pull request by joao-p-marques**
@Tecnativa
TT30382

ping @pedrobaeza @Yajo

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This misses:

- A migration script that empties current status from any company.
- Empty company_id in current data.
- Not directly related, but I see that the data doesn't have `force_create=False` for allowing to remove them. ¿Or maybe it's better to be demo data?

**Comment by joao-p-marques** [comment]
Ok, changes made @pedrobaeza 

> ¿Or maybe it's better to be demo data?

IMHO it makes more sense as regular data, but without `forcecreate`, as suggested...

**Review by pedrobaeza — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's not bump the version 2 times:

/ocabot merge nobump

**Pull request merged**
