### PR TITLE
[11.0][ADD] project_timeline_task_dependency: Arrows between dependencies

### PR DESCRIPTION
**Pull request by tarteo**
Uses the attribute introduced here: https://github.com/OCA/web/pull/1020

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by astirpe — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Adding the dependency to a task should automatically print the flag in the timeline, right? I cannot get that.

**Comment by tarteo** [comment]
@aheficent It's dependent on https://github.com/OCA/web/pull/1020 so currently it doesn't work yet. After https://github.com/OCA/web/pull/1020 is merged the arrow will indeed automatically be printed.

**Review by AaronHForgeFlow — COMMENTED** [review]
@tarteo It works now :) let's wait for the dependency to get merged before merging this.

**Comment by pedrobaeza** [comment]
Merging as everything is clear although it's not still working until we merge the other PR.

**Pull request merged**
