### PR TITLE
[14.0][FIX] project_forecast_line: context in settings action

### PR DESCRIPTION
**Pull request by ntsirintanis**
Fixes action that erroneously directs to General Settings menu

### CODE REVIEW

**Review by gjotten — APPROVED** [review]
Yeah I wondered why this was going wrong in the frontend.

**Review by thomaspaulb — APPROVED** [review]
@ntsirintanis If you declare yourself `maintainer` of this module in manifest, then you can also use the OCAbot to merge in stuff.

**Comment by gjotten** [comment]
@OCA/project-service-maintainers not sure if Nikos' putting himself in as module maintainer is going to help on this PR yet, so someone else should probably patch merge here.

**Comment by alexey-pelykh** [comment]
@gjotten it would help only after the change of adding maintainer is merged, not before. I'm not in a position to review the maintainer declaration yet otherwise looks good.

**Review by alexey-pelykh — APPROVED** [review]
Change LGTM, maintainer declaration - no idea

**Comment by leemannd** [comment]
IMO if he is willing to participate and help maintaining this module, we shouldn't block him.

**Review by leemannd — APPROVED** [review]

**Comment by leemannd** [comment]
@ntsirintanis If you are willing to participate in maintaining this module, can you port your modification into the maintainers in other versions of the module?

**Comment by ntsirintanis** [comment]
> @ntsirintanis If you are willing to participate in maintaining this module, can you port your modification into the maintainers in other versions of the module?

Thank you very much @leemannd for merging this.

My plan is to backport all project_forecast_line modules from 15.0 to 14.0, and also push a series of new modules, based on project_forecast_line, to 14.0. I will be then the maintainer of all 14.0 modules + for any potential forward-ports. As far as I am aware of, project_forecast_line modules for version 15.0 and beyond are already maintained by the original authors.

**Pull request merged**
