### PR TITLE
[17.0][MIG] project_administrator_restricted_visibility: Migration to 17.0

### PR DESCRIPTION
**Pull request by Abranes**
Standard migration to 17.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
/ocabot migration project_administrator_restricted_visibility

**Review by hitrosol — APPROVED** [review]
Functionally tested.
Maybe can we prevent non original PM add additional member ? because it will open to other member that sometimes the original PM doesn't want to share to the one s/he wants to work with ?

**Review by jaenbox — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
