### PR TITLE
[16.0][IMP] project_task_code Search by code in x2m

### PR DESCRIPTION
**Pull request by ivs-cetmix**
Search task by its code in x2m fields.
Supersedes https://github.com/OCA/project/pull/1241

### CODE REVIEW

**Review by flotho — APPROVED** [review]
Hi,

Thanks for this so pure code.
One line of code and so many tests ;)

**Comment by ivs-cetmix** [comment]
> Hi,
> 
> Thanks for this so pure code. One line of code and so many tests ;)

Hi @flotho , less code - less bugs 😆 
@rvalyi could you please check this too?

**Review by rvalyi — APPROVED** [review]

**Comment by ivs-cetmix** [comment]
@rvalyi  thank you! Dear @OCA/project-service-maintainers would be great to have this merged!

**Review by alexey-pelykh — APPROVED** [review]

**Pull request merged**
