### PR TITLE
[14.0][MIG] project_deadline

### PR DESCRIPTION
**Pull request by newtratip**
- `resource_calendar_id` is doesn't have in the project view on V.14. I move `Start Date` and `Expiration Date` into group `extra_settings`
- No need to enable debug mode with `Start Date` and `Expiration Date` 

cc: @ecosoft-odoo

### CODE REVIEW

**Review by benbrich — APPROVED** [review]
After a quick journey on runbot, I can send functional thumbs up. Thanks for the work!

**Review by lfreeke — APPROVED** [review]
LGTM :+1: (Functional test)

**Comment by newtratip** [comment]
@OCA/project-service-maintainers Should this merged ? Is there PSC member concern to fix this ?

**Comment by simahawk** [comment]
@astirpe good for you?

**Pull request merged**
