### PR TITLE
13.0 mig project parent task filter

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@schout-it @astirpe and @Saran440 could you re-review this PR (It is the same that you have approved in #595)

**Review by astirpe — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]

**Comment by emagdalenaC2i** [comment]
@pedrobaeza this is ready. Please, merge it.
I want to create a new migration PR here to verify if the issue I had with pre-commit in my last 2 PR in other repositories will happend again

**Pull request merged**
