### PR TITLE
[13.0][MIG] project_stage_state

### PR DESCRIPTION
**Pull request by Saran440**
Standard Migration

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Review by dalonsod — CHANGES_REQUESTED** [review]
Code review and tested. Only two things:
- did you consider a little improvement like adding `state` field to Task and Stage search views?
- missing squashing commits for v12 commit history

**Comment by Saran440** [comment]
@dalonsod 
- I didn't improve in this PR. But it's good idea to improve in next PR after this module merged.
- Fixed

Thank you for your reviewed. :)

**Review by HaraldPanten — APPROVED** [review]
It seems to be working fine. Functional review.

By the way... I agree with @dalonsod if it's not too much work improving these features. Just a suggestion, non blocking.

**Comment by Saran440** [comment]
@HaraldPanten Okay, I already add state in search view 1 commit for cherry-pick this to V12. Could you review please?

**Comment by HaraldPanten** [comment]
Still looking good to me 👍

**Pull request merged**
