### PR TITLE
[ADD] Project Type Module

### PR DESCRIPTION
**Pull request by patrickrwilson**
Adds Project Type Module which provides a way to add project types to the project object.

### CODE REVIEW

**Comment by patrickrwilson** [comment]
Original Discussion #500

**Comment by patrickrwilson** [comment]
I'm not exactly sure why this is failing due to this error: 

2019-04-18 21:14:37,060 6476 ERROR openerp_test odoo.sql_db: bad query: b'ALTER TABLE "project_project" ALTER COLUMN "project_type_id" SET NOT NULL'
ERROR: column "project_type_id" contains null values.

Any insight would be appreciated.

**Comment by max3903** [comment]
@patrickrwilson The field is required:
https://github.com/OCA/project/pull/502/files#diff-a6821d7bc2e9ca91cd0f974468ecabc7R10

and the project module provides demo data which have an empty value.

One option to solve this is to set a value in the `pre_init_hook`.

Here is an example:
https://github.com/OCA/product-attribute/blob/11.0/product_code_mandatory/__manifest__.py#L17
https://github.com/OCA/product-attribute/blob/11.0/product_code_mandatory/__init__.py#L7

**Comment by pedrobaeza** [comment]
I see this very similar to https://github.com/OCA/project/tree/12.0/project_category in the purpose.

**Comment by patrickrwilson** [comment]
Thank you max3903, I understand the required field issue now. pedrobaeza, you are correct, that module does server our needs and this would essentially be a duplicate of that one. Sorry I missed that when I was looking for this. I do like how that module works on tasks too. 

How do I go about cancelling this pull request since the module is no longer needed?

**Comment by pedrobaeza** [comment]
I close the PR then.

**Pull request closed without merging**
