### PR TITLE
[12.0] porting project_task_digitized_signature

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Review by mrcast — APPROVED** [review]
Porting approved!

**Review by Saran440 — APPROVED** [review]
Functional Test, LGTM :+1: 
please, could you squash your commits into 1?

**Comment by eLBati** [comment]
@Saran440 done

**Comment by AlexisTonneau** [comment]
Hello ! I can see in your manifest some dependencies : 
`"depends": [
        "project_task_report",
        "web_widget_digitized_signature",
    ]`
Where can we find them ?

**Comment by eLBati** [comment]
@AlexisTonneau I suggest to search them through https://odoo-community.org/shop

**Comment by eLBati** [comment]
@OCA/project-service-maintainers merge?

**Comment by JayVora-SerpentCS** [comment]
@pedrobaeza can you help ?
Thanks,

**Comment by pedrobaeza** [comment]
Can't we use now native signature widget?

**Comment by eLBati** [comment]
@pedrobaeza do you mean in `web_widget_digitized_signature`?

**Comment by pedrobaeza** [comment]
I mean that there may be not need of `web_widget_digitized_signature` at all.

**Comment by dreispt** [comment]
Can you please ellaborate @pedrobaeza ?

**Comment by pedrobaeza** [comment]
Odoo already includes a widget for digitizing signature. You can see it when accepting the sales order in the portal. My point is that this may be reusable for this.

**Comment by eLBati** [comment]
@pedrobaeza right.
Having already released `web_widget_digitized_signature` for v12, I would go on with this PR and propose the switch for v13, see https://github.com/OCA/web/pull/1538#issuecomment-640524200

**Comment by pedrobaeza** [comment]
OK, as you prefer, as I'm not an active user of this module anymore.

**Comment by eLBati** [comment]
@OCA/project-service-maintainers merge?

**Pull request merged**
