### PR TITLE
[15.0][FIX][project_timeline] can not open the menu Tasks Analysis

### PR DESCRIPTION
**Pull request by CoraVanga**

### CODE REVIEW

**Comment by quannguyen1560** [comment]
Can you please explain why we have this issue or why do you remove them?

**Comment by CoraVanga** [comment]
I remove the action because it was used to add the view_mode `timeline` to model `report.project.task.user`.
but it did not define the timeline view for `report.project.task.user` => Error.

I think we don't need to have timeline view for `report.project.task.user` because we already have timeline view for `project.task`

**Review by quannguyen1560 — APPROVED** [review]
LGTM

**Review by zamberjo — CHANGES_REQUESTED** [review]
Hi! that view was added on https://github.com/OCA/project/pull/1160

**Comment by pedrobaeza** [comment]
Closing as already fixed.

**Pull request closed without merging**
