### PR TITLE
[14.0][MIG] project_task_digitized_signature

### PR DESCRIPTION
**Pull request by ChristianSantamaria**
Migration to v14
Based on PR #802 and with dependencies on [OCA/project-reporting/tree/14.0/project_task_report](https://github.com/OCA/project-reporting/tree/14.0/project_task_report)

### CODE REVIEW

**Review by bodedra — CHANGES_REQUESTED** [review]
Thanks for your efforts. Wrong way module migration. See reason https://github.com/OCA/project/pull/802#issuecomment-1180673683

**Review by bodedra — COMMENTED** [review]
Functional reviewed. Working as expected on task.

Pending points/carry forward comments from v13 migration: 

Here is TODO list for replicate same behavior in Sale Order:

-   [ ] Add signature template in Task portal view
-   [ ] Send "Print Task" report in a Task chatter area.

**Comment by dalonsod** [comment]
> Pending points/carry forward comments from v13 migration

You're right, added `ROADMAP` file to migration to v13 commit.

**Comment by dalonsod** [comment]
@victoralmau could you review? Thanks!

**Comment by victoralmau** [comment]
> @victoralmau could you review? Thanks!

Sorry, I don't have time right now to review it, and I also don't know it.

**Comment by dalonsod** [comment]
@bodedra @pedrobaeza could you approve it, or still are pending tasks for this PR? Thanks in advance!

**Comment by pedrobaeza** [comment]
I let it to @bodedra, as I'm not using this module anymore.

**Review by bodedra — APPROVED** [review]
Code review. LG 👍

**Comment by dalonsod** [comment]
@cubells could you review? Thanks!

**Comment by bodedra** [comment]
@OCA/project-service-maintainers Would you please review it?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The dependency over `project_task_report` is overkilled. This base module mustn't depend on the other.

**Comment by dalonsod** [comment]
I don't understand, that module is already used here:

https://github.com/solvosci/project/blob/cb113b04aa3f8da85979ac1667c8b1124ff80367/project_task_digitized_signature/report/project_task_report.xml#L3-L6

This functionality (adding signature to task report) comes from previous module versions. What dou you say, removing such functionality, that should be implemented in other module?

**Review by pedrobaeza — APPROVED** [review]
OK, I see, sorry. I didn't know why it was introduced, but it's from the beginning, so I'm not opposing:

/ocabot merge nobump

**Pull request merged**
