### PR TITLE
[16.0][MIG] project_timeline_hr_timesheet: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa TT43238

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
ping @pedrobaeza

**Review by CarlosRoca13 — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Hi, the progress bar is not being shown in any place:

Selección_095

Selección_096

Check previous versions to see how it appeared

**Comment by Yadier-Tecnativa** [comment]
We need to merge PR https://github.com/OCA/web/pull/2525 before this to show class and styles in Html nodes

**Comment by pedrobaeza** [comment]
Can you repush for having an updated runboat now that the other PR is merged?

**Comment by Yadier-Tecnativa** [comment]
Done

imagen

**Review by stefan-tecnativa — APPROVED** [review]

**Review by CarlosRoca13 — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
