### PR TITLE
[10.0][MIG]project_category backport to 10.0

### PR DESCRIPTION
**Pull request by guilhom34**

### CODE REVIEW

**Comment by flotho** [comment]
Hi @oca-clabot ,

@guilhom34 is part of Mind And Go organizatio which already signed the CLA. Does it still necessary to sign the CLA as an individual ?

Regards

**Comment by alexey-pelykh** [comment]
@flotho specific github ID needs to be mentioned in CLA, as far as I remember

**Comment by bodedra** [comment]
Please, preserve commit history. Thanks!

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by guilhom34** [comment]
Hello @pedrobaeza,

I sent the CLA and add the Mind and go address to my account. Do you need anything else ?

Regards

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0, but inverting branches 10.0/11.0, and then you will need to find some reviewers for the PR.

**Pull request closed without merging**
