### PR TITLE
[9.0][project_description] Migrate from v8

### PR DESCRIPTION
**Pull request by yajo**
Almost no changes.

@Tecnativa @rafaelbn

### CODE REVIEW

**Comment by dreispt** [comment]
:+1:

**Comment by rafaelbn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by dreispt** [comment]
Pedro, although this seems a trivial PR, please don't merge so fast.
We should leave some time for other people to comment.

**Comment by pedrobaeza** [comment]
Again this conversation? The module has 3 approvals (even one not of my team), so there's no need for that. Don't fall again on the same thing.

**Comment by dreispt** [comment]
Well, you already know my opinion here.
It should really be discussed on the proper place - I'll open the discussion as soon as I find some time for that.

**Comment by pedrobaeza** [comment]
Ok, you can start a discussion to change the current rules if you want, but take into account that:

1) We are following the rules
2) This is totally incoherent with your optimistic merge proposal
3) The current problem with OCA is the lack of contributors for reviewing, which is not a problem in my team, that always review our work between each other. If you try to block this option, you'll be obstructing the OCA itself.

**Pull request merged**
