### PR TITLE
[16.0][MIG] project_task_description_template: Migration to 16.0

### PR DESCRIPTION
**Pull request by Tisho99**
Standard migration.
V17 and v15 have same commits so the original migration branch is irrelevant

### CODE REVIEW

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
@luis-ron @Jaimermaccione could u review please?

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM

**Comment by HaraldPanten** [comment]
@etobella @pedrobaeza Do you mind helping us merging this simple module?

THX!

**Pull request merged**
