### PR TITLE
[FIX] project_double_alias: Remove linked second aliases on unlink

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @Tecnativa

**Comment by sergio-teruel** [comment]
:+1: Seems oks

**Review by antespi — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
@dreispt please review to get your "valid" approval :wink:

**Review by rafaelbn — APPROVED** [review]
OK

**Comment by pedrobaeza** [comment]
I have also added the corresponding part on the tests for not dropping coverage.

**Comment by pedrobaeza** [comment]
@dreispt Please squash and merge after reviewing

**Comment by dreispt** [comment]
:+1:

**Pull request merged**
