### PR TITLE
[17.0][MIG]project_timesheet_time_control: Migration to 17.0

### PR DESCRIPTION
**Pull request by RogerSans**
Supersede = https://github.com/OCA/project/pull/1230
Standard migration.
T-6446

@HaraldPanten 
@ValentinVinagre 
@luis-ron

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@pedrobaeza The original PR seems to be abandoned.

Could you assign this one to Roger and close the superseded original one?

THX.

**Review by dreispt — APPROVED** [review]

**Review by luis-ron — APPROVED** [review]
Functional Review: LGTM 👍🏻

**Pull request merged**
