### PR TITLE
[ADD][10.0] analytic_account_sequence

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Generate an automatic and unique WBS code for the WBS structure

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this should be in OCA/account-analytic

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza I added it here because it strongly depends on project_wbs but I don't mind to move it to OCA/account-analytic

**Comment by pedrobaeza** [comment]
Then change the module name, and you have conflicts in the code.

**Comment by AaronHForgeFlow** [comment]
Actually this does not depends on project_wbs but the other way around, project_wbs needs a unique sequence. Moved to account-analytic here: https://github.com/OCA/account-analytic/pull/164

**Pull request closed without merging**
