### PR TITLE
[17.0][MIG] project_task_add_very_high

### PR DESCRIPTION
**Pull request by ygol**
Standard migration to 17.0

### CODE REVIEW

**Review by gaikaz — APPROVED** [review]

**Review by flotho — APPROVED** [review]
functionanl test on runboat
LGTM

**Review by arquero20022 — APPROVED** [review]
LGTM

**Comment by BT-jmichaud** [comment]
When will this PR be merged?

**Comment by BT-mfasola** [comment]
would love to see this merged

**Pull request merged**
