### PR TITLE
[IMP][15.0] project_parent_task_filter

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@mariadforgeflow @tarteo and @AaronHForgeFlow Please, could you review this PR?

**Review by mariadforgeflow — APPROVED** [review]
LGTM! Code and functional review.

**Review by AaronHForgeFlow — COMMENTED** [review]
Playing around in runbotat I get an error when creating a subtask on a recent created subtask from the kanban view:

```
  File "/mnt/data/odoo-addons-dir/setup/project_parent_task_filter/odoo/addons/project_parent_task_filter/models/project_task.py", line 23, in action_subtask
    default_project = self.project_id.subtask_project_id or self.project_id
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'project.project' object has no attribute 'subtask_project_id'
```

I guess this is a corner case but it would be nice to check if it can be solved.

**Comment by emagdalenaC2i** [comment]
@AaronHForgeFlow done

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM :+1:

**Comment by emagdalenaC2i** [comment]
@OCA/project-service-maintainers Please, could you merge this PR?

**Pull request merged**
