### PR TITLE
12.0 mig project task material stock

### PR DESCRIPTION
**Pull request by osimallen**
New PR to replace https://github.com/OCA/project/pull/545

### CODE REVIEW

**Comment by rafaelbn** [comment]
Thanks @osimallen . I set need fixing because runbot and travis are :red_circle:

**Comment by osimallen** [comment]
If anyone has suggestions for how to resolve the runbot failing, please let me know. The logs don't seem to be available so I am having trouble determining why it is failing.

**Comment by pedrobaeza** [comment]
I have rebuild the runbot, and here you have the problem:
```
2019-08-29 22:59:43,026 171 WARNING openerp_test odoo.addons.base.models.ir_model: Two fields (analytic_account_id, analytic_account_active) of project.task() have the same label: Analytic Account.
```

**Comment by rafaelbn** [comment]
Hi @osimallen  check https://github.com/OCA/project/pull/572#issuecomment-526394667  for the error to be fixed

**Comment by rafaelbn** [comment]
Please @osimallen could you please squash commits?

**Comment by osimallen** [comment]
@osi-scampbell @max3903 Can you guys review this please?

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍 

@max3903 @ValentinVinagre @osimallen @osi-scampbell

**Review by ValentinVinagre — APPROVED** [review]
Code review, maybe you could add more tests and squash the last commit, but for me it's okay 👍

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by antoniocanovas — APPROVED** [review]
Functional test OK.

**Pull request merged**
