### PR TITLE
[16.0][MIG] project_key

### PR DESCRIPTION
**Pull request by vincent-hatakeyama**
Supersedes #1169 with multi create.

### CODE REVIEW

**Review by hspl-priva — APPROVED** [review]

**Review by hspl-niharika — APPROVED** [review]

**Comment by patel1008b** [comment]
@vincent-hatakeyama thanks for the migration. @dreispt tested works okay, I think we can merge this.

**Comment by dreispt** [comment]
Superseded by #1210

**Comment by vincent-hatakeyama** [comment]
I’ve rebased and will try to fix the failing tests. It seems to be an incompatibility between this module and another.

**Comment by vincent-hatakeyama** [comment]
I’ve fixed the issues in the migration that made other modules tests fail.

**Comment by vincent-hatakeyama** [comment]
@dreispt You should be able to ask the bot to resume merging now that the tests are running correctly.

**Review by dreispt — APPROVED** [review]

**Pull request merged**
