### PR TITLE
Scrum Project Module 

### PR DESCRIPTION
**Pull request by mohamedhabibchallouf**
Hey Daniel ,
as agreed previously by mail I just committer the scrum module 
Thank You

### CODE REVIEW

**Comment by pedrobaeza** [comment]
AFAIK, this should go to https://github.com/OCA/project-agile

**Comment by mohamedhabibchallouf** [comment]
https://github.com/OCA/project-agile still empty i cannot fork this reposi tory

**Comment by pedrobaeza** [comment]
@dreispt haven't you finished the project initialization?

**Comment by dreispt** [comment]
@pedrobaeza just learned about it...

**Comment by dreispt** [comment]
@mohamedhabibchallouf Can you try now?

**Comment by mohamedhabibchallouf** [comment]
Moved to Project Agile Branch

**Comment by sbidoul** [comment]
@pedrobaeza @dreispt initialization of project-agile is not finished. Actually I was waiting for the OCA representative's CLA (ok now), and membership (pending).

**Pull request closed without merging**
