### PR TITLE
[MIG] project_stage_closed : Migration to 13.0

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
I'm assuming you have used `black` formatter, isn't it?

**Comment by Saran440** [comment]
@pedrobaeza Sorry, What is black formatter?

**Comment by pedrobaeza** [comment]
Oh, then you have replaced all the quotes by hand?

**Comment by Saran440** [comment]
Yes, I replaced quote manifest.py by hand.
Do you have any suggestions?

**Comment by pedrobaeza** [comment]
Well, that kind of stylistic stuff in migrations is not recommended, or at least not in the same commit, as changes needed for migrating the module are lost between the rest of the changes.

**Comment by Saran440** [comment]
okay, I backward code to original.
Thank you.

**Review by emagdalenaC2i — APPROVED** [review]

**Pull request merged**
