### PR TITLE
Add code health indicator

### PR DESCRIPTION
**Pull request by dreispt**
Experimental support for landscape.io continuous code health monitoring.

### CODE REVIEW

**Comment by yvaucher** [comment]
Interesting

Some requirements might be missing:
https://landscape.io/github/OCA/project-service/1/messages/error

**Comment by dreispt** [comment]
The why the "experimental" bit is there. :wink: 
In fact, we need the `prospector` checker to follow the same rules used in TravisCi for pep8 and pylint checks.
I have [asked about this](https://github.com/landscapeio/landscape-issues/issues/83) and it's possible by adding a `.prospector.yaml` file. So it's something to fine tune.

**Comment by yvaucher** [comment]
Ok thanks for the details.

**Comment by dreispt** [comment]
I would love to see this merged, so that we can follow how it behaves.

**Comment by pedrobaeza** [comment]
I would like to know how health is measured, but of course we should have a test repo, and it can be this, that you're the main responsible, so I fast track the PR. We can revert it later if any trouble.

**Comment by dreispt** [comment]
Code health improved +21% after this merge :grin: 
https://landscape.io/github/OCA/project-service/3

**Pull request merged**
