### PR TITLE
[14.0][MIG] project_list: Migration to 14.0

### PR DESCRIPTION
**Pull request by skeller1**
Standard migration, no changes compared to V13

project_list_mig14

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
I don't know if this module is needed or if it just need some kind of refactoring. See
Project_list

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@emagdalenaC2i didn't get your point, you're showing that same result can be achieved by editing manually, so...?

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by emagdalenaC2i** [comment]
@alexey-pelykh I mean this module brings little added value and maybe could be merge into another one

**Comment by skeller1** [comment]
> I don't know if this module is needed or if it just need some kind of refactoring. See
> Project_list

AFAIU the current xml is the way to extend the view. I don't know an other way to add tree to view_mode. This would be overriding maybe :thinking: 
Could you please provide a snippet. Thank you

**Comment by emagdalenaC2i** [comment]
Forget this. I was thinking of adding more functionality to this module or merging it with some other module.
But I can't think of a better option

**Review by emagdalenaC2i — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I'm afraid we have exhausted the Travis new rate limits for free accounts, so we need to rethink the CI across OCA.

**Comment by alexey-pelykh** [comment]
@pedrobaeza that sounds pretty critical. GitHub actions as per that email thread?

**Comment by pedrobaeza** [comment]
Yes, that can be the way.

**Pull request merged**
