### PR TITLE
8.0 project_gtd

### PR DESCRIPTION
**Pull request by sebalix**
The `project_gtd` module has been removed from Odoo 8.0, and this PR aims to integrate this module to OCA.
The last version of the source code of the module has been retrieved from the 8.0 branch, then fixed/cleaned/improved a bit.
Translations are not updated yet (I don't know if there is a tool to manage that since the Github migration).

It seems that the build fails against the `service_desk_issue` module.

### CODE REVIEW

**Comment by dreispt** [comment]
That was fixed by #18 - I just merged it, you should rebase your PR.
Also, there are a couple of PEP8 issues to be fixed.

**Comment by sebalix** [comment]
That's done. I was using Pylint which does not show the same errors that flake8. PR updated, all seems fine.

**Comment by dreispt** [comment]
No point in reviewing the source in detail, since in comes from the official modules...
With TravisCI green, LGTM :+1:

**Comment by pedrobaeza** [comment]
I agree with Daniel. :+1:

**Comment by sebalix** [comment]
Great, thank you.

**Pull request merged**
