### PR TITLE
Merge 'OCA/contract/6.1' into 'OCA/project-service/6.1'

### PR DESCRIPTION
**Pull request by dreispt**
As discussed at https://github.com/OCA/contract/issues/1.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: All are additions, so nothing to discuss.

Regards.

**Comment by dreispt** [comment]
Yep. It's great it's so easy to do this with git. :bowtie:

**Comment by guewen** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
