### PR TITLE
[15.0][MIG] project_duplicate_subtask

### PR DESCRIPTION
**Pull request by mariadforgeflow**
Standard Migration to v15.
Child tasks of subtasks weren't duplicated: added recursive function that runs through all the children duplicating them as well.

@ForgeFlow

### CODE REVIEW

**Review by tarteo — APPROVED** [review]
LGTM, tested locally. Only comment I have is when I duplicate a record the normal way it updates the javascript model with the new record, and opens the record in edit mode.
With 'Duplicate with subtasks' it's different.

Before:
image

After normal duplicate:
image


After "Duplicate with subtasks":

image


But for me this is small ux issue, not that important

**Comment by mariadforgeflow** [comment]
Hi @tarteo! I have updated the PR. After duplicate a task it opens the new record in edit mode, the js issue I don't know how to fix it. 
Also, I noticed that child tasks of subtasks weren't duplicated, now there is a recursive function that runs through all the children duplicating them as well.
If you could check it now with this changes I would appreciate it a lot. Thanks!

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by tarteo — APPROVED** [review]
LGTM! Thanks

**Comment by mariadforgeflow** [comment]
@dreispt hi!! Could you try to merge it again please? thx!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Now with github actions I think it won't give silly errors. @dreispt @tarteo could you merge?

**Pull request merged**
