### PR TITLE
[17.0] [FIX] project_timeline: Add list view on projects

### PR DESCRIPTION
**Pull request by ByteMeAsap**
The module replaced the list view for projects with timeline view. This Pr aims to add the list view back

### CODE REVIEW

**Comment by ByteMeAsap** [comment]
@pedrobaeza , its the same in v17 as was in v16.

**Review by pedrobaeza — APPROVED** [review]

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
Hi @pedrobaeza I think that we can move forward with this one

**Pull request merged**
