### PR TITLE
[7.0] Try to fix building errors

### PR DESCRIPTION
**Pull request by katyukha**
Some times on version 7.0 it resoves same errors (model is not
initialized correctly, or at right time)

Just a try...

### CODE REVIEW

**Comment by katyukha** [comment]
This approach have no sense here(

**Comment by pedrobaeza** [comment]
That's not needed, so there must be another problem. Do you have a traceback?

**Comment by katyukha** [comment]
[Travis build](https://travis-ci.org/OCA/project-service/jobs/47304301)
Seems that odoo loads views in incorect order, model was not loaded.

**Comment by katyukha** [comment]
seems to be builded correctly.

**Comment by katyukha** [comment]
changes from here moved to #48, so there no need to keep separate pull request.

**Pull request closed without merging**
