### PR TITLE
[15.0][REM] project_milestone

### PR DESCRIPTION
**Pull request by remytms**
Milestones are present in module `project` starting from 15.0 and scripts that exists in this empty module does not work.

See #1267 

See also https://github.com/OCA/OpenUpgrade/pull/4397

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]
Migration is covered in OpenUpgrade

**Comment by pedrobaeza** [comment]
Isn't this only a placeholder for the migration scripts?

**Comment by rvalyi** [comment]
> Isn't this only a placeholder for the migration scripts?

it doesn't seem so as per the comments in #1267

so removing the module seems legit.

**Review by pedrobaeza — APPROVED** [review]
OK

/ocabot merge nobump

**Comment by sebalix** [comment]
[`project_template_milestone`](https://github.com/OCA/project/blob/15.0/project_template_milestone/__manifest__.py) in this repository is still referencing this removed module, but the CI is happy with that, weird :thinking:

**Pull request merged**
