### PR TITLE
13.0 mig project budget

### PR DESCRIPTION
**Pull request by hitrosol**
simple migration

### CODE REVIEW

**Comment by hitrosol** [comment]
i don't understand why runboat is not running, while other checks are passed.

**Comment by bunhin** [comment]
I have a functional test on run_boat, and ok. Let's merge it.

**Review by gurneyalex — APPROVED** [review]

**Review by leemannd — APPROVED** [review]
Hello, thank you for the migration.
Usually we split the migration in two commits:
- pre-commit hook
- migration commit

**Pull request merged**
