### PR TITLE
[14.0][MIG] project_wbs

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Looks good overall, can you remove the strings from the buttons in the WBS list? 

image

**Comment by JasminSForgeFlow** [comment]
> Looks good overall, can you remove the strings from the buttons in the WBS list?
> 
> image

Done, Thanks

**Review by AaronHForgeFlow — COMMENTED** [review]
Creating subprojects from the list is good. However, When using the button there is no way to change the code, resulting in this error. There must be something else, because the subproject created, even if it has the same code, it should not have the same complete_wbs_code. 

project_wbs

**Comment by JasminSForgeFlow** [comment]
> Creating subprojects from the list is good. However, When using the button there is no way to change the code, resulting in this error. There must be something else, because the subproject created, even if it has the same code, it should not have the same complete_wbs_code.
> 
> project_wbs [ project_wbs ](https://user-images.githubusercontent.com/19620251/218730847-8bf779e2-3a83-4d6f-ba46-bef09b350056.gif) [ ](https://user-images.githubusercontent.com/19620251/218730847-8bf779e2-3a83-4d6f-ba46-bef09b350056.gif)

Fixed.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review LG!

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM

**Pull request merged**
