### PR TITLE
[12.0] [ADD] project_task_milestone

### PR DESCRIPTION
**Pull request by dalonsod**
This module extends Task, adding the ability to set the task as a milestone,
the ability to classify the task by phase and sequence and to access directly
from the current project to it's own task

### CODE REVIEW

**Review by lromero-solvos — APPROVED** [review]
Functionally LGTM

**Review by ovnicraft — APPROVED** [review]

**Comment by ovnicraft** [comment]
LGTM

**Comment by pedrobaeza** [comment]
This requires a Project PSC to confirm the addition.

**Comment by rafaelbn** [comment]
Please @dalonsod could you please take a look in https://github.com/OCA/project/issues/500 , thank you!

**Comment by patrickrwilson** [comment]
@dalonsod can you explain the difference between this module and the project_milestone module?

**Comment by dalonsod** [comment]
@patrickrwilson maybe the module name is a bit confusing, as "task milestone" is only a part of its functionallity. My brief description, emphatising differences with `project_milestone`:

- Adds phases to tasks for task classification. Task phase definition is general, project non-dependent, so every phase is available for every task.
- Task milestone is only a check, and you can filter by it.
- The module also provides the project task plan, as a view using the related task stage, and task start and end dates. This utility is shown in its own menu, as well as within a project form, in many ways (e.g. gantt view).

@oihane can you review this?

**Review by patrickrwilson — APPROVED** [review]

**Comment by rafaelbn** [comment]
Hello @dalonsod ,

Please take you comment   and add an Usage section like https://github.com/OCA/project/tree/12.0/project_milestone#usage in order to test it.

I would like to test it but in this moment for me you say

> add phases to task for task classification

This for me are stages and tags! so I don't undestand phases. Stages are project non-dependent
And in any case module would be project_task_phase

> Task milestone is only a check

Is a check in task o in the phases?

> This module provides the project taks plan

This is https://github.com/OCA/project/tree/12.0/project_timeline


It look like you are adding several functionalities in the same module and should be splitted and the most important duplicating functionalities of existing modules

If you provide and usage section it will be easier for contributors to test it as commented

**Review by rafaelbn — CHANGES_REQUESTED** [review]
I would like to test functionaly

**Comment by ovnicraft** [comment]
> Hello @dalonsod ,
> 
> Please take you comment and add an Usage section like https://github.com/OCA/project/tree/12.0/project_milestone#usage in order to test it.
> 
> I would like to test it but in this moment for me you say
> 
> > add phases to task for task classification
> 
> This for me are stages and tags! so I don't undestand phases. Stages are project non-dependent
> And in any case module would be project_task_phase

Yes, phases in project are stages.
IMO phases concept duplicate stages functionality.

> 
> > Task milestone is only a check
> 
> Is a check in task o in the phases?
> 
> > This module provides the project taks plan
> 
> This is https://github.com/OCA/project/tree/12.0/project_timeline
> 
> It look like you are adding several functionalities in the same module and should be splitted and the most important duplicating functionalities of existing modules
> 
> If you provide and usage section it will be easier for contributors to test it as commented

**Pull request closed without merging**
