### PR TITLE
[10.0]-[IMP/ADD]-Added Child Project Smart button in parent project module

### PR DESCRIPTION
**Pull request by YogeshMahera-SerpentCS**
[PR Reference](https://github.com/OCA/business-requirement/pull/231#issuecomment-336192508)

### CODE REVIEW

**Comment by YogeshMahera-SerpentCS** [comment]
@elicoidal Could you please review it

**Review by elicoidal — APPROVED** [review]
LGTM.
One question: it looks weird to me that the module does not depend on account_analytic_parent. It works but some fields or views are not present.
I would suggest to fix the dependency (in this PR or in another)

**Review by dreispt — APPROVED** [review]
LGTM. I restarted the build to confirm its all good.

**Comment by astirpe** [comment]
Rebase the branch. The Travis failure should be fixed now.

**Comment by YogeshMahera-SerpentCS** [comment]
Rebased!
Now Travis is Happy

**Pull request merged**
