### PR TITLE
[11.0] [MIG] project_list: Backport from 13.0 to 11.0

### PR DESCRIPTION
**Pull request by yweng8111**
I just did the Backport of module project_list.

### CODE REVIEW

**Comment by yweng8111** [comment]
There are already a Backport of it. Sorry, I have to check it at first. But It seems that nothing was happened since Sep. 2019.
https://github.com/OCA/project/pull/576

**Comment by yweng8111** [comment]
@OCA/project-service-maintainers, How can I get some detailed Information about the failed checks for runbot ?

**Review by marylla — APPROVED** [review]
I made a functional review. The list view is now available for projects (Projects > Dashboard).
Looks good to me. :+1: 

@yweng8111 I am not sure if this helps you but you can open the logs, if you click on runbot details, then on the gear-icon and then "Full base logs" or "Full all logs". I just saw that there are deprecation warnings for some libraries but I dont know if this is the failure reason.

**Comment by yweng8111** [comment]
@marylla Thanks for the Tips, But I also didn't understand that errors.
@gurneyalex Can you help me?

**Review by chandni299 — APPROVED** [review]
Code Review :+1:

**Comment by yweng8111** [comment]
@OCA/project-service-maintainers Can you please check this?

**Pull request merged**
