### PR TITLE
[14.0][MIG] project_role

### PR DESCRIPTION
**Pull request by Yoshiro009**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@Yoshiro009 thanks for your PR! Why is the submodule needed?

**Comment by newtratip** [comment]
@alexey-pelykh, submodule no need. I remove it. Can you review this again please ?

**Edited**
1. Change module version from v.13 to v.14
2. Remove migration script
3. Change `track_visibility="onchange"` to `tracking=True`
4. name="toggle_active" replaced by name="web_ribbon" Archived (Project Assignments, Project Roles)
5. Filter `Inactive` rename to `Archived` on Project Assignments

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Review by fshah-initos — APPROVED** [review]
Functional and code review Looks good to me

**Comment by fshah-initos** [comment]
Can this PR be merged hence it is approved?

**Review by alexey-pelykh — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
