### PR TITLE
[17.0][MIG] project_task_description_template

### PR DESCRIPTION
**Pull request by alan196**
Standard module migration from V15 to V17

### CODE REVIEW

**Review by GasparJarsa — APPROVED** [review]
LGTM

**Comment by leemannd** [comment]
Hello @alan196 , Thanks for the migration. Runbot and translation commits should be squashed.

**Comment by alan196** [comment]
@leemannd I squashed the translation commit and bot commit

**Review by leemannd — APPROVED** [review]

**Pull request merged**
