### PR TITLE
[16.0][MIG] project_sequence: Migration to version 16.0

### PR DESCRIPTION
**Pull request by NICO-SOLUTIONS**
standard migration

### CODE REVIEW

**Review by antoniocanovas — APPROVED** [review]
Functional review OK !!

**Review by moitabenfdz — APPROVED** [review]
LGTM

**Comment by leemannd** [comment]
Hello @NICO-SOLUTIONS , Thank you for your contribution.
There is still one little step required. Could you squash together administrative commits and commit related to translations?

**Review by leemannd — APPROVED** [review]
LGTM Waiting for the squashing of adminstrative/translation commits before merge

**Comment by NICO-SOLUTIONS** [comment]
translations into the IMP pre-commit stuff commit?
Unbenannt

**Comment by leemannd** [comment]
Into this wiki, you'll find all main point to be done during migration, especially a full (long) explanation on the squashing of commits -> https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

**Comment by NICO-SOLUTIONS** [comment]
@leemannd 
do you mind to have a look to it, if i have done it correct?

**Comment by leemannd** [comment]
Hello, it seems something went wrong with rebase. There are a lot of commits that aren't related to this migration

**Comment by NICO-SOLUTIONS** [comment]
> Hello, it seems something went wrong with rebase. There are a lot of commits that aren't related to this migration

That's because my translation commits do not refer to the migration of this module. Translations referring to other modules of this repo. That's why I was confused by squashing suggestion.

**Comment by NICO-SOLUTIONS** [comment]
> Hello, it seems something went wrong with rebase. There are a lot of commits that aren't related to this migration

@leemannd 
as is think this probably was a misunderstanding. i switched back to the previous state (with fresh rebase onto 16.0). If i understood correctly. the translation commits have to be squashed in general (as well as administrative commits). As the translations made by me are referred to other modules, i think sqashing them is not the right way here.

If there is anything unclear to me, please open my eyes. Sorry for the hassle... Still improving my git skills. Learned a lot about interactive rebasing now ;P

**Comment by pedrobaeza** [comment]
Let me show you graphically the expected squashing:

Selección_141

**Comment by NICO-SOLUTIONS** [comment]
@pedrobaeza 
Thanks you pedro for the graphical explanation. I was focussed to much on the translations. Got it now! 

@leemannd 
sorry for the hassle

**Comment by leemannd** [comment]
@NICO-SOLUTIONS Thank you for the work

**Pull request merged**
