### PR TITLE
[12.0][IMP] project_timeline - Enable subtasks

### LINKED ISSUE #485: [IMP] project_timeline: Timeline view & Subtasks
Currently, the timeline view does not distinguish tasks and subtasks. 
It would be nice to have a filter to show only the parent tasks (without subtasks), as defined in #347 

Also, when accessing the subtasks of a specific task, the timeline view is not available.

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
Fixed #485

### CODE REVIEW

**Review by tarteo — APPROVED** [review]
Thanks!

**Comment by emagdalenaC2i** [comment]
@tarteo I think you are right and I need to add a menu item. But I am not sure how to do that

**Comment by emagdalenaC2i** [comment]
Ok now it's fine. I had forgotten the project. suffix

I'll sort and simplify a bit, then I'll wait for your comments and squash all the commits

@tarteo and @pedrobaeza In addition to making it work for the subtasks, I have recovered the Activities view that are lost in the current version.

**Comment by ovnicraft** [comment]
LGTM

**Comment by emagdalenaC2i** [comment]
@pedrobaeza commits squashed and ready to review and merge

**Review by nikul-serpentcs — APPROVED** [review]
Code Review LGTM :+1:

**Pull request merged**
