### PR TITLE
[15.0][FIX] project_stock: Set the warehouse_id field correctly.

### PR DESCRIPTION
**Pull request by victoralmau**
Related to https://github.com/OCA/project/issues/1042

Set the `warehouse_id` field correctly.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Are you sure this one is not needed in 14.0?

**Comment by victoralmau** [comment]
Yes, in v14 we use https://github.com/odoo/odoo/blob/14.0/addons/stock/models/stock_location.py#L156-L160

**Pull request merged**
