### PR TITLE
[12.0][IMP] project_role: revert manual options in favor of web_m2x_options

### PR DESCRIPTION
**Pull request by alexey-pelykh**
@pedrobaeza what do you think of this?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Well, you can leave it this way and take note for newly modules, but don't mind removing it again.

**Comment by alexey-pelykh** [comment]
I won't be able to sleep good if I'll leave it as is :)

**Review by pedrobaeza — APPROVED** [review]
OK then, all for your sleep health!

**Comment by pedrobaeza** [comment]
But please indicate also that the system parameter should be put.

**Comment by alexey-pelykh** [comment]
Added to the readme

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
Please don't forget this https://github.com/OCA/project/pull/452#issuecomment-487146507 for v13 :smile:

**Pull request merged**
