### PR TITLE
[11.0][MIG]project_description

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history. You have to follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by emagdalenaC2i** [comment]
ok, thanks

**Review by Jerther — APPROVED** [review]
LGTM.

I don't know if all the different copyright comments here and there are relevant though.

Please review this PR if you can: https://github.com/OCA/project/pull/328

**Comment by pedrobaeza** [comment]
Please respect commit history following the migration guide:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by emagdalenaC2i** [comment]
Ok, I was looking for this PR to close it ;-)

**Pull request closed without merging**
