### PR TITLE
[15.0][MIG] project_timesheet_time_control: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT37806

This PR superseds: https://github.com/OCA/project/pull/939

please @pedrobaeza @sergio-teruel review this

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@CarlosRoca13 please check if all the changes from #1003 are here

**Comment by CarlosRoca13** [comment]
Now all changes from https://github.com/OCA/project/pull/1003 were added.

**Comment by sergio-teruel** [comment]
Check pre-commit 
Tests are failing due to project_task_personal_stage_auto_fold module

**Comment by wildi1** [comment]
There is also one bug in my scenario. Starting a timer in task's kanban view, will cause, that all tasks are folded after the wizard get's confirmed. See this video:
@CarlosRoca13 Can you reproduce that ? 

https://user-images.githubusercontent.com/24716841/200083597-25b7dcbd-af35-4d42-a0c7-64d7f285eefc.mp4

**Comment by pedrobaeza** [comment]
That's not something of this module, but ir_act_window_reload

**Comment by wildi1** [comment]
Are you sure to "web_ir_actions_act_view_reload", or could it also be "web_ir_actions_act_multi".
I found, that there are some cases where the tasks don't get folded. I could also capture it. But it is not constantly reproduceable. 

https://user-images.githubusercontent.com/24716841/200090069-11250024-0d72-414b-991e-8704ec4adfb6.mp4

**Comment by pedrobaeza** [comment]
Well, I can't say for sure, but it's related to that ones, not this module itself.

**Comment by wildi1** [comment]
@pedrobaeza How to continue with that? Opening an issue in the OCA/web repository with the description from obove?

**Comment by pedrobaeza** [comment]
Yes, that can be the option.

**Comment by pedrobaeza** [comment]
@CarlosRoca13 there's a mix of the diffs in the last 2 commits, and no cherry-picking of latest PRs of older versions, but they are introduced in the last commit.

**Comment by CarlosRoca13** [comment]
Changed @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
