### PR TITLE
[MIG] project_template: Migration to 13.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by okuryan — APPROVED** [review]

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
Hi @alfadil 

It seems that it exists an incompatibility with project_key module. I describe the behaviour:

1- Open the options of a project and set "is template" checkbox to True.
2- Once the project has been defined as a template, click to "Create project from template". It doesn't matter if you do that by the form view or the Kanban view. It will work properly.
3- Try to create a second project using the same template as before: An error occurs as a restriction popup will tell the user that "Project key must be unique".

If you create one project from a template it is working fine. If you try to create a second project using the same template, user is going to be restricted by the unique key.

Could you check?

Thanks!

**Comment by ghost** [comment]
hi @HaraldPanten 
the incompatibility with project_key module is inherited problem from previous versions, And frankly I think the user should change the name of the project generated from project template rather than trying to change the behavior of one of the modules 
Thanks for your comment

**Review by HaraldPanten — APPROVED** [review]
It's OK then.

Functional review 👍

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Pull request merged**
