### PR TITLE
[12.0] Standard OCA pre-commit config and others

### PR DESCRIPTION
**Pull request by marcelsavegnago**
for now I have marked all modules to be ignored by pre-commit

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@OCA/tools-maintainers Can someone help me? :) Any idea helps

https://github.com/OCA/project/actions/runs/4166539123/jobs/7210996619#step:6:5

**Comment by pedrobaeza** [comment]
You should change the maturity level of `project_timesheet_time_control` to Beta, or disable such check (it's a copier question).

**Comment by marcelsavegnago** [comment]
> You should change the maturity level of `project_timesheet_time_control` to Beta, or disable such check (it's a copier question).

Thanks @pedrobaeza

**Comment by marcelsavegnago** [comment]
ping @OCA/project-service-maintainers

**Comment by marcelsavegnago** [comment]
ping https://github.com/orgs/OCA/teams/project-service-maintainers

**Review by rousseldenis — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
