### PR TITLE
[14.0][FIX] project_role: `image_small` -> `image_128`

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
...

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
I take it relates to [58a2ffa26f1a3b0f9630ce16d11b758d18e20a21](https://github.com/odoo/odoo/commit/58a2ffa26f1a3b0f9630ce16d11b758d18e20a21)?

**Comment by MiquelRForgeFlow** [comment]
Yes...

**Comment by alexey-pelykh** [comment]
Though that changes small to 64? Just asking, not requesting any change

**Comment by MiquelRForgeFlow** [comment]
That's a good question.

**Comment by MiquelRForgeFlow** [comment]
@alexey-pelykh they changed from 64 to 128 in https://github.com/odoo/odoo/commit/b6288e54461426d7aac6cfc549cee3e90309a093

**Review by alexey-pelykh — APPROVED** [review]
LGTM

**Pull request merged**
