### PR TITLE
Adaption of project_task_delegate for v9

### PR DESCRIPTION
**Pull request by ghost**
Ive searched for an alternative to delegate tasks in odoo9 cause Odoo has removed functions, but nothing found.
Here my adaption of task delegation for CE.

regards,
Karsten

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check your PR, as there are 589 files modified. You also need to sign the CLA https://odoo-community.org/page/cla.

Thanks.

**Comment by dreispt** [comment]
Try `git rebase 9.0`

**Comment by ghost** [comment]
Hello Daniel,

it is the first time I constribute to a project and as I can see, I have 
done wrong as I comitted 549 files.
How do I continue and how to correct this?
I have done git rebase 9.0 at my local git repos, which has remote url 
to my forked project and upstream to origin/9.0 of oca project.

Sincerely,
Karsten

Am 17.07.2016 um 00:41 schrieb Daniel Reis:

**Comment by dreispt** [comment]
Try:

```
git fetch upstream 9.0
git rebase upstream/9.0
```

**Comment by dreispt** [comment]
You still have a big diff.
I suggest you create a new clean branch from upstream/9.0 copy into it the new module files, and create a new PR with those changes.

**Comment by dreispt** [comment]
Can you point us to the new PR please?

**Comment by ghost** [comment]
https://github.com/OCA/project/pull/185

Am 20.07.2016 um 15:06 schrieb Daniel Reis:

**Pull request closed without merging**
