### PR TITLE
[14.0][BACKPORT] project_forecast_line_holidays_public from 15.0 to 14.0

### PR DESCRIPTION
**Pull request by ntsirintanis**
Depends on https://github.com/OCA/project/pull/975

### CODE REVIEW

**Comment by gurneyalex** [comment]
please check https://github.com/OCA/project/pull/977

**Comment by thomaspaulb** [comment]
@ntsirintanis Should this be reopened?

**Comment by ntsirintanis** [comment]
> @ntsirintanis Should this be reopened?

yeah, let's try to reopen this one

**Comment by thomaspaulb** [comment]
@OCA/project-service-maintainers Can this be reopened?

**Comment by simahawk** [comment]
@thomaspaulb is not possible. We need a new PR.

**Pull request closed without merging**
