### PR TITLE
[ADD][11.0] Adding module project_portal

### PR DESCRIPTION
**Pull request by pnajman-modoolar**
Hello,

Module ``project_portal`` overrides methods of the project portal controller to make them more usable for other modules.

Kind Regards,
Petar

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't like this too much, because this makes any derivative module from this one incompatible with the rest. You should propose to Odoo that hooks instead.

**Comment by pnajman-modoolar** [comment]
Due to the comment of @pedrobaeza I'm closing this pull request

**Comment by LoisRForgeFlow** [comment]
@pnajman-modoolar Did you propose any PR to odoo? could you point them?

**Comment by pnajman-modoolar** [comment]
Not yet but i'll definitely do that ...

**Pull request closed without merging**
