### PR TITLE
[MIG] project_task_code to 11.0

### PR DESCRIPTION
**Pull request by rodrigets**

### CODE REVIEW

**Comment by aldo774** [comment]
LGTM :+1:

**Review by mstuttgart — APPROVED** [review]
LGTM :+1:

**Review by aldo774 — APPROVED** [review]
LGTM :+1:

**Comment by pedrobaeza** [comment]
Have you signed CLA?

**Comment by rodrigets** [comment]
Yes :+1:

**Review by feketemihai — APPROVED** [review]

**Comment by rodrigets** [comment]
Good afternoon, @pedrobaeza.
Is there any correction to be made?

**Comment by pedrobaeza** [comment]
Did you sign CLA?

**Comment by rodrigets** [comment]
Yes, I sent the completed form twice.

**Comment by pedrobaeza** [comment]
OK, this one can be merged then.

**Pull request merged**
