### PR TITLE
[10.0][project_task_code] Backport the name get structure to display task code in task name

### PR DESCRIPTION
**Pull request by flotho**

### CODE REVIEW

**Comment by flotho** [comment]
Hi @pedrobaeza , it looks like travis triger some environment issues.

sorry if you're not the appropriate person to ping

**Comment by pedrobaeza** [comment]
Update .travis.yml with latest definition from https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml in a new PR for fast merging once green, and rebase this.

**Comment by rafaelbn** [comment]
Please @flotho could you review travis? is :red_circle:

**Review by dreispt — APPROVED** [review]
LGTM

**Pull request closed without merging**
