### PR TITLE
[15.0][MIG] project_timeline_hr_timesheet: Migration to 15.0

### PR DESCRIPTION
**Pull request by chandni299**

### CODE REVIEW

**Review by quannguyen1560 — APPROVED** [review]
LGTM!

**Review by victoralmau — APPROVED** [review]
Code and functional review OK

**Comment by victoralmau** [comment]
Please **abort**, does not work correctly in v14 and v15
Example of v13
ejemplo-4

**Comment by pedrobaeza** [comment]
And what happens in v15?

**Comment by victoralmau** [comment]
Please cherry pick https://github.com/OCA/project/pull/1082 to commit history (before the migration commit)

**Comment by victoralmau** [comment]
Can you apply the cherry-pick to be able to merge it?

**Comment by victoralmau** [comment]
Superseed: https://github.com/OCA/project/pull/1088

**Pull request closed without merging**
