### PR TITLE
[14.0][ADD] new module: project_forecast_line_milestone

### PR DESCRIPTION
**Pull request by ntsirintanis**
Related and based on https://github.com/OCA/project/pull/1238 https://github.com/OCA/project/pull/1248

### CODE REVIEW

**Review by gjotten — APPROVED** [review]
:+1: functional review

**Comment by ntsirintanis** [comment]
@NL66278 @thomaspaulb please take a look and let's try to merge this one too

**Review by dreispt — APPROVED** [review]

**Review by gjotten — APPROVED** [review]

**Comment by thomaspaulb** [comment]
Looks like runbot has some issues, we should retry the merge once they are solved.

**Pull request merged**
