### PR TITLE
[10.0][MIG] project_double_alias

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Standard migration
* Fix test

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@luismontalba @chienandalu please review

**Review by chienandalu — COMMENTED** [review]
@pedrobaeza I can't get to show email tab on project configurations. Is there anything else needed to set up?

**Comment by pedrobaeza** [comment]
You have to configure some system parameters referred to the catchall domain and alias. Please figure out and I'll add the instructions in configuration.

**Review by chienandalu — APPROVED** [review]
@pedrobaeza Right. In addition to `mail.catchall.domain`, `mail.catchall.alias` needs to be configured as well.

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Review by dreispt — APPROVED** [review]

**Pull request merged**
