### PR TITLE
[12.0][IMP] project_role: possible roles

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Allows depending modules to more consistently get list of roles that are available to particular user on particular project, taking into account inheritance and other advanced features.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Explanation of the change?

**Comment by alexey-pelykh** [comment]
@pedrobaeza added

**Comment by alexey-pelykh** [comment]
@tarteo if possible, please review

**Comment by pedrobaeza** [comment]
I'm feeling the module is getting very complicated for not such a difficult feature, but I can't judge. What I can ask is for 2 things:

- Add docstrings to methods for knowing what they do. For example, what `_check` does?
- Expand README for all the new stuff.

**Comment by alexey-pelykh** [comment]
Technically, added method is exposing what is already there - company-wide assignments that were added as we discussed previous improve. Why it's added: because when other modules need list of roles that user can assume, they would need to manually implement company-wide assignments inheritance, and that would get error-prone.

**Comment by alexey-pelykh** [comment]
@pedrobaeza adjusted readme and added some docstring on non-obvious methods

**Review by artemsenko — APPROVED** [review]

**Comment by artemsenko** [comment]
Functional test LGTM

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
