### PR TITLE
[15.0][MIG] project_role

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@rafaelbn @ajaniszewska-dev @bizzappdev please transfer your opinions here

**Review by bizzappdev — APPROVED** [review]
LGTM

**Comment by ajaniszewska-dev** [comment]
migration commit should be according to template: `[MIG] $MODULE: Migration to 15.0`, same for PR title.

**Comment by alexey-pelykh** [comment]
@ajaniszewska-dev it is?
image

As for the PR title - can you please point me to the rule/requirement in the guidelines, would be great to enhance my knowledge of those.

**Comment by ajaniszewska-dev** [comment]
> @ajaniszewska-dev it is? image
> 
> As for the PR title - can you please point me to the rule/requirement in the guidelines, would be great to enhance my knowledge of those.

@alexey-pelykh  yes - sorry, my bad. but change PR title accordingly please. it is not a strict requirement there but i faced problems because of that when i wanted to merge my OCA PRs recently.

Guideline: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by alexey-pelykh** [comment]
@ajaniszewska-dev sorry, yet I fail to find line in the guide PR title, please point me to the specific line. Also, regarding the issues you've encountered in your PRs - out of curiosity, what PRs are those?

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by ajaniszewska-dev** [comment]
> @ajaniszewska-dev sorry, yet I fail to find line in the guide PR title, please point me to the specific line. Also, regarding the issues you've encountered in your PRs - out of curiosity, what PRs are those?

it is fine as it is, i was looking on wrong commit.

**Comment by alexey-pelykh** [comment]
@ajaniszewska-dev tbh, I'm not sure that demand if you got one about PR title was reasonable, so just curious what PSC team was going for that

**Pull request merged**
