### PR TITLE
[14.0] Migration of project_timeline_hr_timesheet

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module project_timeline_hr_timesheet.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by mariadforgeflow** [comment]
The module works fine, if you open the project_task_timeline view the progress appears in each task. The thing is that the button  to access this view in the Tasks section doesn't appear:
image

**Comment by ChrisOForgeFlow** [comment]
Please @mariadforgeflow review related pr #869 where is resolved issue with window action without timeline view

**Review by ChrisOForgeFlow — APPROVED** [review]
Functional and Code Review Ok

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
