### PR TITLE
[12.0][FIX] project_task_add_very_high: move priority widget before title

### LINKED ISSUE #509: [12.0][IMP]project_task_add_very_high - improve UX
As @rafaelbn mentioned in #501 
UX here is broken in task form view
image

To improve this UX I thing that there must be a view in the module project_task_add_very_high that replace in view_task_form2 the lines:
```
                    <div class="oe_title pr-0">
                        <h1 class="d-flex flex-row justify-content-between">
                            <field name="priority" widget="priority" class="mr-3"/>
                            <field name="name" class="o_task_name text-truncate" placeholder="Task Title..."/>
                            <field name="kanban_state" widget="state_selection" class="ml-auto"/>
                        </h1>
                    </div>
```

for the next ones:
```
                    <field name="priority" widget="priority" class="mr-3"/>
                    <div class="oe_title pr-0">
                        <h1 class="d-flex flex-row justify-content-between">
                            <field name="kanban_state" widget="state_selection" class="ml-auto"/>
                            <field name="name" class="o_task_name text-truncate" placeholder="Task Title..."/>
                        </h1>
                    </div>
```
And this is the result UX
image

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/project/issues/509.

With this PR, here is how it looks like:

image

### CODE REVIEW

**Comment by astirpe** [comment]
@emagdalenaC2i

**Comment by pedrobaeza** [comment]
Why it can't be at the same line? This seems a waste of space.

**Comment by astirpe** [comment]
@pedrobaeza yes, that was my proposal: https://github.com/OCA/project/issues/509#issuecomment-486946090

**Comment by pedrobaeza** [comment]
OK, then go ahead with it in all the modules that makes something similar (this one and project_key?)

**Comment by emagdalenaC2i** [comment]
So, this PR should be closed and create other PR to change the other modules?

**Comment by astirpe** [comment]
Reopening (see discussion in https://github.com/OCA/project/pull/532)

**Review by emagdalenaC2i — APPROVED** [review]
@astirpe if you don't want that the "In Progress/Blocked" widget move to the rigth, then maybe you can change the order: put the kanban state first like as mentioned in #509 

```
                    <field name="priority" widget="priority" class="mr-3"/>
                    <div class="oe_title pr-0">
                        <h1 class="d-flex flex-row justify-content-between">
                            <field name="kanban_state" widget="state_selection" class="ml-auto"/>
                            <field name="name" class="o_task_name text-truncate" placeholder="Task Title..."/>
                        </h1>
                    </div>
```

**Comment by astirpe** [comment]
@emagdalenaC2i Cool, thanks!
It seems that changing `class="ml-auto"` to `class="mr-auto"` for field `kanban_state` does the trick, without the need of moving the field.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza so, could you review/approve this PR?

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
