### PR TITLE
[17.0][MIG] project_task_default_stage: Migration to 17.0

### PR DESCRIPTION
**Pull request by jaydeep32**

### CODE REVIEW

**Review by sonhd91 — COMMENTED** [review]
Non-blocking but might need squashed some commit, please take a look at [squash commits guidline](https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate)

**Review by sonhd91 — APPROVED** [review]

**Review by tien-ld — APPROVED** [review]
LGTM

**Pull request merged**
