### PR TITLE
Project Phase

### PR DESCRIPTION
**Pull request by Guillaumeleclercqbhc**
Project Phase Module

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please review https://github.com/OCA/maintainer-tools/tree/master/template/module, there is not README file. Thanks

**Comment by dreispt** [comment]
Thank you for subitting your work to OCA.
There's some work here before we can review:
- Make Travis happy; start by checking the lint errors
- Remember to squash your commits before asking for reviews
- Can it be split into smaller PRs? Big PRs tend to stall because they are very hard to review.

**Comment by dreispt** [comment]
@Guillaumeleclercqbhc Are you planning working on this?

**Comment by houssine78** [comment]
Hi @Guillaumeleclercqbhc,

the project_phase look like some part have been bringing back to life from project_long_term an abandoned project from Odoo. I'm sure phasing is something we need! So are you planning to work on this PR soon or later?

But my main remark here is about the licensing... On which it seems we have a serious issue about licensing infringement... From what I see, big part(all?) of the code is just  copy/paste from Odoo SA... 

So Odoo SA should remain as the author and at least co-author on this module same goes for the licensing. BHC could add his name as contributor and as owner of the code it has added but not for the whole piece of code. same goes for the project_phase on your repo

**Comment by dreispt** [comment]
@houssine78 I guess @Guillaumeleclercqbhc is not working on this.
If you like, you can pick up the PR and also fix those license issues.

**Comment by rafaelbn** [comment]
You can take a look in https://github.com/projectexpert/pmis/blob/f4242092fd9976b473f2eb9bc59d835c3a9cfeee/project_wbs/README.rst#L23, also work with phase in project. Here @jbeficent can help.

**Comment by emagdalenaC2i** [comment]
This PR has not changed for more than 2 years. @OCA/project-service-maintainers Should it be closed?

**Comment by simahawk** [comment]
@Guillaumeleclercqbhc feel free to reopen if needed :wink:

**Pull request closed without merging**
