### PR TITLE
[MIG][10.0]project_wbs

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Tasks done so far:
- rename __openerp__.py to __manifest__.py
- change readme and version in the manifest

### CODE REVIEW

**Review by pmartineznetquest — APPROVED** [review]
Reviewed testing parent and child projects (created from the scratch), the analytic hierchary and the resulting analytic entries. Also checked with existing projects.

**Comment by sysadminmatmoz** [comment]
Done some work here - not familiar with inter branch pull requests thou, so check it [here](https://github.com/luximgroup/project/tree/10.0). Cleaned up the xmls (to follow the version 10 user experience) and some code (since the up/down arrows navigation in the tree and kanban didn't fuction properly with the existing one - when you try to navigate down on a project that has no child, it still has to open the related view to be able to encode new sub-projects - with my commits it works as expected.

**Comment by AaronHForgeFlow** [comment]
@sysadminmatmoz Thank you for those improvements. Do you mind if I include those in this PR?

**Comment by sysadminmatmoz** [comment]
That's why I posted here :) Be my guest

**Comment by sysadminmatmoz** [comment]
All checks OK 😄

**Comment by AaronHForgeFlow** [comment]
@sysadminmatmoz Don't you think it's ok to keep the navigation up?

**Comment by sysadminmatmoz** [comment]
On kanban yes, on list view no, since it's meant just to open a new list view to encode several lines (project_ids), and with the parent (nav up) there can be only one. (I'm talking as someone that actually uses the database, not just codes it).

**Comment by AaronHForgeFlow** [comment]
@sysadminmatmoz I still think the navigation up in list view is useful. When searching from some child project we may need to get to the parent quickly instead of going to the form view and then to the parent.

**Comment by bennals** [comment]
@aheficent I'm just starting to look at this module (used it on v8) and am wondering if the wbs code should be automatically generated and unique - currently it's possible to have duplicated wbs codes?

**Comment by AaronHForgeFlow** [comment]
@bennals Yes, we use this module together with project_sequence

**Comment by bennals** [comment]
@aheficent ah, I see. Is that an OCA module or available anywhere else?

**Comment by AaronHForgeFlow** [comment]
@bennals Actually, the module is analytic_account_sequence, here we are using the hierarchy of the analytic accounts not the one for projects. I though wrongly that it was in OCA, sorry for the misunderstanding. I'll propose a PR to https://github.com/OCA/account-analytic and I'll let all know here.

**Comment by AaronHForgeFlow** [comment]
@bennals see the PR for the analytic_account_sequence here: https://github.com/OCA/project/pull/374
It will need some cleaning. @sysadminmatmoz

**Comment by bennals** [comment]
thanks @aheficent.  Will check it out.

**Comment by bennals** [comment]
@aheficent another quick question - do you use a module that allows searching for tasks based on the full wbs code so you can see all tasks in a project hierarchy at once?

**Comment by AaronHForgeFlow** [comment]
@bennals Yes, but it's still v8: https://github.com/Eficent/pmis/tree/8.0/project_wbs_task

**Review by MiquelRForgeFlow — APPROVED** [review]
@aheficent please squash commits

**Comment by AaronHForgeFlow** [comment]
squashed and rebased

**Pull request merged**
