### PR TITLE
Add to Tasks their Project Code

### PR DESCRIPTION
**Pull request by dreispt**
The Project's code can be used to implement business logic automation
rules that are independent from Project database IDs.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1: 

Question: is this fields visible anywhere?

**Comment by dreispt** [comment]
@bwrsandman No. I'm using it for Filters and  Automated Actions, to avoid using database Ids.

**Comment by veloutin** [comment]
:+1:

**Pull request merged**
