### PR TITLE
[14.0][mig] project_task_project_required

### PR DESCRIPTION
**Pull request by HekkiMelody**
Nothing to do on the migration except replace some tabs with spaces

### CODE REVIEW

**Comment by leemannd** [comment]
Hello @aleuffre Thank you for the migration. Is it possible to squash administrative/translation commits?

**Comment by HekkiMelody** [comment]
> Hello @aleuffre Thank you for the migration. Is it possible to squash administrative/translation commits?

done! Thank you for reopening this.

**Review by leemannd — APPROVED** [review]

**Pull request merged**
