### PR TITLE
[14.0] [MIG] project_purchase_link

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by skeller1** [comment]
Maybe you could add missing test code from #744  to pass pipeline.
Thank you for supporting OCA

**Comment by patrickrwilson** [comment]
@emagdalenaC2i thanks for your PR, can you finish it by adding additional test coverage? Then I'll be happy to review.

**Comment by Freni-OSI** [comment]
Hi @emagdalenaC2i, Can you clear this Travis failing? Thanks.

**Comment by Chanakya-OSI** [comment]
Hi, @emagdalenaC2i Can You make Travis Happy and Rebase it? Thanks

**Comment by rafaelbn** [comment]
Hello @emagdalenaC2i , you have reviews and comments here, could attend or answer please? Thank you!

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@Urvisha-OSI Since we have no answer from @emagdalenaC2i, can you superseed this PR?

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Since we have no answer from @emagdalenaC2i, can you superseed this PR?

@max3903 i checked for it but this is a private repo and i don't have access of the clone so i can't work on it

**Comment by max3903** [comment]
@Urvisha-OSI Let's redo the migration and close this PR.

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Let's redo the migration and close this PR.

@max3903 use this PR for prohect_purchase_link module migration
https://github.com/OCA/project/pull/1034

**Comment by rafaelbn** [comment]
/ocabot rebase

@emagdalenaC2i please could you attend travis?

**Pull request closed without merging**
