### PR TITLE
[16.0][MIG] project_task_pull_request: Migration to 16.0

### PR DESCRIPTION
**Pull request by Volodiay622**
reopening from [stale PR](https://github.com/OCA/project/pull/1137)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please start from the work already done in the other PR, only adding the missing stuff.

**Comment by ivs-cetmix** [comment]
> Please start from the work already done in the other PR, only adding the missing stuff.

hi @pedrobaeza  could you have a look at this please? If everything is done right. Thank you in advance!

**Comment by pedrobaeza** [comment]
OK, the other seems to not have clear author, so I suppose this is enough.

/ocabot migration project_task_pull_request

**Review by geomer198 — APPROVED** [review]
LGTM!

**Review by DemchukM — APPROVED** [review]
LGTM

**Pull request merged**
