### PR TITLE
[IMP] Search project tasks with code

### PR DESCRIPTION
**Pull request by TimLai125**
Define `name_search()` for `project.task` therefore user can search tasks by the `code` field on m2o fields.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@TimLai125 no need to include version bump commit, it will be done during merging

**Review by alexey-pelykh — CHANGES_REQUESTED** [review]
Check now negative terms are handled in https://github.com/OCA/project/blob/12.0/project_key/models/project_task.py#L84

**Review by alexey-pelykh — CHANGES_REQUESTED** [review]
Please squash all the commits into one

**Review by alexey-pelykh — APPROVED** [review]

**Review by yostashiro — APPROVED** [review]

**Review by flotho — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
@dreispt ocabot stuck on merge

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
