### PR TITLE
16.0 mig project risk

### PR DESCRIPTION
**Pull request by jumeldi74**
Migration to 16

### CODE REVIEW

**Comment by jumeldi74** [comment]
Migration from version 12 to version 16

**Comment by moitabenfdz** [comment]
Please, squash the administrative commits.
https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

**Review by moitabenfdz — APPROVED** [review]
LGTM

**Comment by patrickkappertqubiq** [comment]
and will there be a version of project risk for odoo 15 and 14?

**Pull request closed without merging**
