### PR TITLE
[12.0][IMP] project_task_dependency: added button to open  dep. task.

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Comment by elvise** [comment]
Great!

PR V14: [Link](https://github.com/OCA/project/pull/961)

**Comment by elvise** [comment]
@pedrobaeza looks good! 
What do you think ?

**Review by elvise — APPROVED** [review]
Perfect!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
