### PR TITLE
[16.0][MIG] project_task_material: Migration to 16.0

### PR DESCRIPTION
**Pull request by valjaro**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@valjaro Could you just follow this https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to

As you should have two commits (one for pre-commit stuff and one for effective migration). Thanks

**Comment by NICO-SOLUTIONS** [comment]
functional review... Looks good to me

**Comment by rousseldenis** [comment]
@valjaro Do you mind if we switch to #1151 ?

**Comment by valjaro** [comment]
> @valjaro Do you mind if we switch to #1151 ?

Yeah np I close this PR!

**Pull request closed without merging**
