### PR TITLE
[12.0][IMP] project_task_pull_request: PR URI in main task view

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Comment by francesco-ooops** [comment]
Backporting to 12 of #934

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

**Review by SicurSam — APPROVED** [review]
Functional review ok!

**Comment by pedrobaeza** [comment]
Doing this change for such old version is not the best for stability.

**Comment by francesco-ooops** [comment]
> Doing this change for such old version is not the best for stability.

ok, we can close this one then :)

**Pull request closed without merging**
