### PR TITLE
[MIG] project_issue_code to v10

### PR DESCRIPTION
**Pull request by thinkwelltwd**

### CODE REVIEW

**Comment by thinkwelltwd** [comment]
The PR includes all Mike's commits for moving to v9. Not sure why that is. I tried to follow the directions in the [Migration to version 10.0](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch), but must be doing something wrong.

If you'll enlighten me what happened, I'll try to fix it.

**Comment by pedrobaeza** [comment]
The problem you had is because that PR is not yet merged, so the remote indicated in the migration guide doesn't serve.

**Comment by thinkwelltwd** [comment]
Well, I'm confused because the PR says it's [Merged](https://github.com/OCA/project/pull/204). But anyway, I'm not too familiar with Git in a collaborative environment; mostly a solo dev.

If you want me to revoke or change this PR, let me know.

**Comment by pedrobaeza** [comment]
Yeah, you're right. It has been recently merged. Maybe you don't fetch latest data before doing this?

**Comment by thinkwelltwd** [comment]
Will close this and start fresh.

**Pull request closed without merging**
