### PR TITLE
[14.0][MIG] project_stock_request.

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@AmmarOfficewalaSerpentCS can you fix pre-commit then I'll review.

**Comment by patrickrwilson** [comment]
@AmmarOfficewalaSerpentCS in addition to the pre-commit fix, can you squash those automated commits in history? (translations, .po, readme)

**Comment by AmmarOfficewalaSerpentCS** [comment]
@patrickrwilson 
I have updated a code 
can you please review ?

**Review by patrickrwilson — APPROVED** [review]
Tested and works great, LGTM

**Review by smangukiya — APPROVED** [review]
TESTED. works good.

**Pull request merged**
