### PR TITLE
[10.0][REM] project_closing removal (became obsolete)

### LINKED ISSUE #353: [RFC] Module project_closing became obsolete?
I'm noticing that all the PRs (both 10.0 and 11.0) opened during the last four weeks have the Travis tests failing.

The travis logs say:
```
FAIL: test_analytic_toggle_active (odoo.addons.project_closing.tests.test_project.TestProject)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/project/project_closing/tests/test_project.py", line 40, in test_analytic_toggle_active
`     self.assertFalse(self._analytic1.active)
` AssertionError: True is not false
FAIL: test_project_toggle_active (odoo.addons.project_closing.tests.test_project.TestProject)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/project/project_closing/tests/test_project.py", line 24, in test_project_toggle_active
`     self.assertFalse(self._analytic1.active)
` AssertionError: True is not false
FAILED
```

Indeed four weeks ago there was a commit (https://github.com/odoo/odoo/commit/055f8e0fcdca7c279642c1e35fe0a1ecd84a025c) that causes the tests of `project_closing` failing. That commit sets the analytic account to 'archived' when it's related project is archived.

It seems that the functionality provided by module `project_closing` is the same introduced by commit https://github.com/odoo/odoo/commit/055f8e0fcdca7c279642c1e35fe0a1ecd84a025c. Does that commit obsolete module `project_closing`?

In any case, all the recent Travis tests are failing because of this and all the new PRs are red.

### PR DESCRIPTION
**Pull request by astirpe**
This is a proposal to remove module project_closing from 10.0 branch.
Backport of https://github.com/OCA/project/pull/356
Motivation and discussion is here: #353
Fixes #353

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Do you know why Travis fail?

**Comment by astirpe** [comment]
Travis OCB job says:

```
ParseError: "External ID not found in the system: portal.partner_demo_portal" while parsing /home/travis/OCB-10.0/addons/project_issue/data/project_issue_demo.xml:36
```

It's because the standard `portal` module is not installed, but required by the demo data of `project_issue`.

Probably this error is caused by PR https://github.com/OCA/OCB/pull/650.

I looked around a bit and I found this: https://github.com/OCA/OCB/issues/682

**Comment by astirpe** [comment]
And anyway, the travis failure is obviously not related with this PR.

**Comment by astirpe** [comment]
@simahawk @pedrobaeza @emagdalenaC2i May I ask you to apply your approval (you already approved https://github.com/OCA/project/pull/356) to this backport?
The red OCB is getting fixed.

**Review by mpanarin — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Restarted Travis now that OCA/OCB#691 has been merged

**Comment by pedrobaeza** [comment]
It's still red. Are you sure is that the problem?

**Comment by astirpe** [comment]
Module portal depends on auth_signup. If auth_signup is not installed, portal doesn't auto-install. But unfortunately also auth_signup was originally auto-installable, and with https://github.com/OCA/OCB/pull/650 it's not anymore. I think that's the problem.

**Review by ghost — APPROVED** [review]

**Comment by simahawk** [comment]
@astirpe @pedrobaeza any update on this? Can we force the installation of needed modules just in tests? Or, can we provide a replacement for that demo data? Or... pick one :wink:

**Comment by astirpe** [comment]
I would prefer to restore the auto-installation of auth_signup. But if you prefer other solutions, I'm ok with that. 
I can create a PR for the auto-installation of auth_signup this afternoon or tomorrow, but if someone can do it sooner, I will immediately approve the PR.

I would like to unlock this situation ASAP ;)

**Comment by pedrobaeza** [comment]
Yes, let's restore that auto-install property.

**Comment by astirpe** [comment]
https://github.com/OCA/OCB/pull/695

**Comment by astirpe** [comment]
Green!

**Comment by simahawk** [comment]
doit

**Comment by astirpe** [comment]
@pedrobaeza may I ask you to merge this one? So that the PRs on branch 10.0 in the project repository will be green again.

**Comment by astirpe** [comment]
Thank you!

**Comment by pedrobaeza** [comment]
You are welcome

**Pull request merged**
