### PR TITLE
Update Travis config and add Transifex

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by dreispt** [comment]
@bwrsandman Transifex [is failing](https://travis-ci.org/dreispt/project-service/jobs/70984643#L161) with a password error. Can you help?

**Comment by bwrsandman** [comment]
It's failing on your repo, the password was made for OCA/project-service so dresipt/project-service fails.

It's a security feature, otherwise anyone could fork the repo and echo the password.

Transifex only runs on pushes not on pull requests for the same reason.

**Comment by bwrsandman** [comment]
Code review :+1:

**Comment by dreispt** [comment]
That makes sense, thanks.

**Comment by tafaRU** [comment]
:+1:

**Comment by bwrsandman** [comment]
https://travis-ci.org/OCA/project-service/jobs/71397600 Still seems like the password is wrong...

**Comment by dreispt** [comment]
I also can't find project-service in Transifex. That could be a cause (or a consequence)?

**Comment by bwrsandman** [comment]
The first transifex build will create the project on transifex. 

Anyway, someone with the transifex password should regenerate a password for `project-service`.

I can probably do this on Monday.

**Comment by bwrsandman** [comment]
Hopefully this one works https://github.com/OCA/project-service/commit/7c6e6f86167f32e940cf9ccf425b0bd8b3d1f19e

**Comment by dreispt** [comment]
We can now see a translation graph on the README, so I guess it did. Thanks!

**Pull request merged**
