### PR TITLE
[14.0][IMP] Update copier 1.20

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@dreispt

**Review by leemannd — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
weird, I though this will solve the issue with the canceled jobs.

**Comment by leemannd** [comment]
Is the configuration taken in account when it is not merged?

Just to check the result, I have relaunched one manually

**Comment by leemannd** [comment]
I don't know where you have the issue, but if I check a PR that has been running recently in `14.0` the github workflow are launched and seems to work -> https://github.com/OCA/project/pull/1254

**Comment by AaronHForgeFlow** [comment]
@leemannd  the trouble is here: https://github.com/OCA/project/pull/1226 I thought it was not related to the PR, is it?

**Pull request closed without merging**
