### PR TITLE
[13.0][FIX] project_task_dependency: recursion error

### LINKED ISSUE #671: Dependency Recursion Causing RecursionError Odoo: 13
Module: Project Task Dependencies
Reproduce Error: Creating recursive dependency causing  RecursionError.

`Error: Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: <NewId origin=43>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('project.task(<NewId origin=43>,).recursive_dependency_task_ids', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6091, in onchange
    for name in nametree
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6092, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5961, in has_changed
    len(self[name]) != len(record[name])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5610, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2290, in __get__
    return super().__get__(records, owner)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1020, in __get__
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1105, in compute_value
    records._compute_field_value(self)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3915, in _compute_field_value
    getattr(self, field.compute)()
  File "/mnt/extra-addons/project_task_dependency/models/project_task.py", line 43, in _compute_recursive_dependency_task_ids
    task.recursive_dependency_task_ids = task.get_dependency_tasks(task, True)
  File "/mnt/extra-addons/project_task_dependency/models/project_task.py", line 60, in get_dependency_tasks
    dependency_tasks |= self.get_dependency_tasks(t, recursive)
  File "/mnt/extra-addons/project_task_dependency/models/project_task.py", line 60, in get_dependency_tasks
    dependency_tasks |= self.get_dependency_tasks(t, recursive)
  File "/mnt/extra-addons/project_task_dependency/models/project_task.py", line 60, in get_dependency_tasks
    dependency_tasks |= self.get_dependency_tasks(t, recursive)
  [Previous line repeated 930 more times]
  File "/mnt/extra-addons/project_task_dependency/models/project_task.py", line 57, in get_dependency_tasks
    dependency_tasks = task.with_context(prefetch_fields=False).dependency_task_ids
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2290, in __get__
    return super().__get__(records, owner)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1048, in __get__
    return self.convert_to_record(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2748, in convert_to_record
    corecords = corecords.filtered('active').with_prefetch(prefetch_ids)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5243, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5243, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5242, in <lambda>
    func = lambda rec: any(rec.mapped(name))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5206, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5165, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5165, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5610, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 996, in __get__
    value = env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 199, in __eq__
    return isinstance(other, NewId) and (
RecursionError: maximum recursion depth exceeded while calling a Python object`

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/project/issues/671

### CODE REVIEW

**Review by davejames — APPROVED** [review]
functional test, LGTM

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
@astirpe Can you please rebase on latest 13.0 and resolve the conflict?

**Comment by astirpe** [comment]
@dreispt done, thanks!

**Comment by astirpe** [comment]
Can this one be merged?

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Was this included in 14.0 branch?

**Comment by astirpe** [comment]
Yes was included in 14.0!

**Comment by pedrobaeza** [comment]
Great, thanks!

**Review by Perfectech-me — COMMENTED** [review]
D

**Comment by Perfectech-me** [comment]
Deome

**Pull request merged**
