### PR TITLE
[15.0][MIG] project_template: migration to `15.0`

### PR DESCRIPTION
**Pull request by Mantux11**
Standard migration to version `15.0`. Odoo deleted subtask project's, so there is made changes also. We don't need to create like a `Subtask Project` anymore.

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]
Code review and functional test by end customer.

Thanks for the migration.

This module is english-only in the way it handles `(TEMPLATE)` and `(COPY)`, but that is an issue which is unrelated to the migration.

**Review by gaikaz — APPROVED** [review]

**Comment by BT-cserra** [comment]
Hello @sbidoul & @gaikaz, can we trigger a merge on this one? Thank you and **have a GREAT DAY**.

**Comment by BT-fgarbely** [comment]
Hello @patrickrwilson @dreispt 

What is the state here? Can this PR be merged?
Thanks for checking.

Have a nice day

**Comment by BT-cserra** [comment]
> /ocabot merge nobump

Hello @dreispt . The merge command failed (or: it did nothing, or nothing that I can see). Can you please try again? Many thanks.

**Pull request merged**
