### PR TITLE
[11.0][MIG] project_milestone:  backport from 12.0 to 11.0

### PR DESCRIPTION
**Pull request by yweng8111**

### CODE REVIEW

**Review by marylla — APPROVED** [review]
I made a functional review and it looks good to me. :+1: 

This is what I did:

* Create a new project and activate the usage of milestone
* Activate the developer mode to edit its stages and set closed = True for the done stage
* Create a milestone for this project
* Create a task and link it to the milestone
* Check the progress of the milestone, which is 0%
* Move the task to stage "Done"
* Check the progress of the milestone, which is 100%

**Review by chandni299 — APPROVED** [review]
Review code :+1:

**Comment by yweng8111** [comment]
@dreispt  Can you please check this?

**Comment by yweng8111** [comment]
@OCA/project-service-maintainers Can you please check this?

**Pull request merged**
