### PR TITLE
[12.0][IMP] Don't allow quick-create on assignments

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
Hi @alexey-pelykh  
Does Runbot work well for you? I get an error trying to evaluate any module of this repository

**Comment by alexey-pelykh** [comment]
@emagdalenaC2i nope, same:
```
The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Error: Invalid CSS after "...    background:": expected expression (e.g. 1px, bold), was "@progress-bar-succe"
        on line 9683 of stdin
>>         background: @progress-bar-success-bg;
   --------------------^
```

**Comment by emagdalenaC2i** [comment]
ok, thx

**Comment by alexey-pelykh** [comment]
I've pinged Pedro about that as well, I believe it's something in OCB repository?

**Comment by pedrobaeza** [comment]
12.0 branch in OCB is exactly the same now than vanilla Odoo (there are no added patches). Maybe an error on Odoo itself.

**Comment by alexey-pelykh** [comment]
Very possible, I wonder what's the raw OCB runbot says.

**Comment by emagdalenaC2i** [comment]
I think the issue is here https://github.com/OCA/project/blob/12.0/project_timeline_hr_timesheet/static/src/scss/project_timeline_hr_timesheet.scss

Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Advertencia		La validación (CSS 4.0): "@" no es un valor válido para la propiedad "background".	Archivos varios	D:\DriveC2i\C2iSource\Odoo\OCA\project\project_timeline_hr_timesheet\static\src\scss\project_timeline_hr_timesheet.scss	12	
Advertencia		La validación (CSS 4.0): "progress-bar-success-bg" no es un valor válido para la propiedad "background".	Archivos varios	D:\DriveC2i\C2iSource\Odoo\OCA\project\project_timeline_hr_timesheet\static\src\scss\project_timeline_hr_timesheet.scss	12	
Advertencia		La validación (CSS 4.0): "@" no es un valor válido para la propiedad "background".	Archivos varios	D:\DriveC2i\C2iSource\Odoo\OCA\project\project_timeline_hr_timesheet\static\src\scss\project_timeline_hr_timesheet.scss	15	
Advertencia		La validación (CSS 4.0): "progress-bar-danger-bg" no es un valor válido para la propiedad "background".	Archivos varios	D:\DriveC2i\C2iSource\Odoo\OCA\project\project_timeline_hr_timesheet\static\src\scss\project_timeline_hr_timesheet.scss	15

**Comment by alexey-pelykh** [comment]
@pedrobaeza any ideas?

**Comment by pedrobaeza** [comment]
@Nikul-Chaudhary you migrated the module. Can you check?

**Comment by emagdalenaC2i** [comment]
I don't know why it is changed in v12.
Here #491 I restore the v11 code

**Review by emagdalenaC2i — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@pedrobaeza is this fix good to go? :)

**Review by bodedra — APPROVED** [review]
Code review :+1:

**Pull request merged**
