### PR TITLE
14.0 mig project key

### PR DESCRIPTION
**Pull request by Yoshiro009**

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
LGTM functional test :+1:

**Comment by newtratip** [comment]
Edited:
- Change version on menifest file from 13.0.1.0.1 to 14.0.1.0.0
- Fix version mock library on python to 3.0.5 (Fix test_controller error)

This PR is ready for review.

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Review by HaraldPanten — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
