### PR TITLE
[FIX]  project_timeline_hr_timesheet scss Issue

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
Code Review :+1:

**Comment by pedrobaeza** [comment]
@Nikul-Chaudhary please explain why you did the change

**Comment by nikul-serpentcs** [comment]
@pedrobaeza as per https://github.com/OCA/project/pull/468#discussion_r262501243  changed `less` to `scss`

**Comment by pedrobaeza** [comment]
Yes, but as you can see in the issues, it has not been correctly converted.

**Comment by emagdalenaC2i** [comment]
So, should we change scss to less again?

Also, checking Travis I see this warning. I am not sure it is related 
0.02s$ travis_after_tests_success
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/travis_after_tests_success", line 5, in <module>
    from coverage.cmdline import main as coverage_main
ImportError: No module named 'coverage'

**Comment by pedrobaeza** [comment]
No, less is deprecated. It should be scss, but correct scss syntax.

**Comment by nikul-serpentcs** [comment]
@tarteo can you please help here
What the correct scss syntax?

**Comment by alexey-pelykh** [comment]
Can we do the formatting proper?
```
.o_project_timeline_hr_timesheet_progress {
    height: 7px;
    background-color: #FFF;
    margin-left: -5px;
    margin-bottom: -5px;
    margin-right: -5px;
    margin-top: 5px;

    > div {
        height: 100%;
        max-width: 100%;
        background: $progress-bar-success-bg;

        &.danger {
            background: $progress-bar-danger-bg;
        }
    }
}

```

**Comment by emagdalenaC2i** [comment]
@alexey-pelykh that's not the right format, Runbot fails too

**Comment by alexey-pelykh** [comment]
@emagdalenaC2i this scss is valid:
```
.o_project_timeline_hr_timesheet_progress {
    height: 7px;
    background-color: #FFF;
    margin-left: -5px;
    margin-bottom: -5px;
    margin-right: -5px;
    margin-top: 5px;

    > .div {
        height: 100%;
        max-width: 100%;
        background: #A;

        &.danger {
            background: #B;
        }
    }
}
```
(check at https://www.sassmeister.com/)

it produces same CSS as this less:
```
.o_project_timeline_hr_timesheet_progress {
    height: 7px;
    background-color: #FFF;
    margin-left: -5px;
    margin-bottom: -5px;
    margin-right: -5px;
    margin-top: 5px;

    > div {
        height: 100%;
        max-width: 100%;
        background: #A;

        &.danger {
            background: #B;
        }
    }
}
```
(check at http://winless.org/online-less-compiler)

**Comment by emagdalenaC2i** [comment]
Ok I think finally we got it.
Thanks @alexey-pelykh

**Comment by emagdalenaC2i** [comment]
close this PR, see #492

**Pull request closed without merging**
