### PR TITLE
14.0 mig project mail chatter

### PR DESCRIPTION
**Pull request by yweng8111**

### CODE REVIEW

**Review by marylla — APPROVED** [review]
I made a functional review.
The chatter is shown and I can schedule activities on project.
LGTM. :+1:

**Review by HaraldPanten — APPROVED** [review]

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok

**Review by angelmoya — APPROVED** [review]
LGTM

**Comment by marylla** [comment]
@dreispt Hi Daniel, would you be so kind to merge this one? :)

**Pull request merged**
