### PR TITLE
[IMP] project_role: add maintainers

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@OCA-git-bot oh you don't say! 🤣

**Comment by pedrobaeza** [comment]
@sbidoul @SimoRubi 2 incoherences here:

- The PR is adding the maintainer, but it's not yet added, so it shouldn't warn.
- The maintainer is the creator of the PR, so it shouldn't warn as well.

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
This part of the bot is very new. First time I see it :) @SimoRubi would you like to have a look at this one?

**Comment by SimoRubi** [comment]
@sbidoul Yes I'd like to look into it, but I don't know when I'll be able to do so..
In the meantime I've opened https://github.com/OCA/oca-github-bot/issues/88 and maybe https://github.com/OCA/oca-github-bot/issues/63 can be closed?

**Comment by sbidoul** [comment]
@SimoRubi sure, no problem. If it becomes too noisy, let me know and I can switch off that feature temporarily.

**Pull request merged**
