### PR TITLE
[13.0][PORT][WIP] 829 from 12.0 ADD project_timesheet_time_control_sale

### PR DESCRIPTION
**Pull request by bosd**
Port #829 from 12.0 to 13.0. add project_timesheet_time_control_sale

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @bosd , is tis still a WIP? Can you pleas update?

**Comment by bosd** [comment]
I am not very actively working on this one.
Will fix pre-commit the coming days so this one can get merged. 

I am actively developing the v14 one. It has more features.
But it may require some code changes on the main module. I dont know how to go about that one.

**Comment by bosd** [comment]
Travis is passing but runboat not. (that is out of my control)
Ok,, let's see how this one goes now.

Feedback appreciated.

**Comment by rafaelbn** [comment]
Hello @eLBati could make a review here please? This is a module you know in v13 😄 really appreciated! Thank you!

**Comment by bosd** [comment]
In the coming days I am hoping to create a draft for the V14 version.

**Comment by bosd** [comment]
ping @eLBati

**Comment by eLBati** [comment]
Hi @rafaelbn hi @bosd , sorry I don't use version 13

**Comment by bosd** [comment]
@AaronHForgeFlow Would you like to review this V13 version as well?

**Review by leemannd — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
