### PR TITLE
Add module sale_to_project

### PR DESCRIPTION
**Pull request by guewen**
This module allows to create a contract from a sales order, with sales order lines (all
or selected) as recurring invoice lines.

It is accompanied with 2 small modules that works together:
1. account_analytic_analysis_layout: adds the `sale_layout` layout fields on the contract recurring lines
2. sale_to_project_layout: copies the `sale_layout` layout fields from sales
   order to contract (autoinstalled when sale_to_project and
   account_analytic_analysis_layout are installed)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think that the module name should be _sale_to_contract_

**Comment by rafaelbn** [comment]
I agree to change name to sale_to_contract.
It has more to do sales with contracts than sales with projects.
And you are creating an account.analytic.account from a sales order, you are not creating a project (the project is created from the account.analytic.account).

**Comment by jgrandguillaume** [comment]
Hi,

Thanks for the contrib. I'm giving my :+1: once the name has changed to sale_to_contract.

Regards,

**Comment by dreispt** [comment]
Since it does not depend on project, IMO this is best suited to go in the OCA/contract repo.

**Comment by dreispt** [comment]
Should we close this?

**Comment by pedrobaeza** [comment]
Closing due to inactivity. If still interested, please reopen.

**Pull request closed without merging**
