### PR TITLE
[12.0][FIX] project_task_add_very_high: prevent conflicts with other modules

### LINKED ISSUE #509: [12.0][IMP]project_task_add_very_high - improve UX
As @rafaelbn mentioned in #501 
UX here is broken in task form view
image

To improve this UX I thing that there must be a view in the module project_task_add_very_high that replace in view_task_form2 the lines:
```
                    <div class="oe_title pr-0">
                        <h1 class="d-flex flex-row justify-content-between">
                            <field name="priority" widget="priority" class="mr-3"/>
                            <field name="name" class="o_task_name text-truncate" placeholder="Task Title..."/>
                            <field name="kanban_state" widget="state_selection" class="ml-auto"/>
                        </h1>
                    </div>
```

for the next ones:
```
                    <field name="priority" widget="priority" class="mr-3"/>
                    <div class="oe_title pr-0">
                        <h1 class="d-flex flex-row justify-content-between">
                            <field name="kanban_state" widget="state_selection" class="ml-auto"/>
                            <field name="name" class="o_task_name text-truncate" placeholder="Task Title..."/>
                        </h1>
                    </div>
```
And this is the result UX
image

### PR DESCRIPTION
**Pull request by astirpe**
Fixes #509.

Before:
image

After:
image

### CODE REVIEW

**Comment by astirpe** [comment]
This fix is not even correct since it moves the "In Progress/Blocked" widget totally to the right.

**Comment by astirpe** [comment]
I'm starting to think that https://github.com/OCA/project/pull/513 was probably a better approach :thinking:

**Comment by emagdalenaC2i** [comment]
I agree

**Comment by pedrobaeza** [comment]
But it needs an extra line...

**Comment by astirpe** [comment]
@pedrobaeza at this moment we have in one single line:

- the priority widget
- the task code
- the task key
- the task name
- the "In Progress/Blocked" widget

and I have the feeling that keeping all this stuff in one single line will be to much demanding in the future for maintaining this simple module.

Imagine if companies using this widget want to add extra priorities (more stars in the widget): if we move the widget to a separate line would be convenient.

**Comment by emagdalenaC2i** [comment]
There are other option... Move the priority to other place
See how it looks in the opportunities form view:
image

**Comment by astirpe** [comment]
Closing in favor of https://github.com/OCA/project/pull/513

**Comment by pedrobaeza** [comment]
I'm talking for not affecting such a critical view for our companies where we access tasks continuously, but if you think it's better to put in other line...

**Comment by emagdalenaC2i** [comment]
@astirpe and @pedrobaeza What do you think of move it like in the opportunities form view? See the picture above

**Comment by astirpe** [comment]
@emagdalenaC2i for me it doesn't really matter. But keeping the widget near the title seems nicer to me. Also the "In progress/Blocked" widget is there. I don't really see any problem to keep it in the top, is not invasive and I don't understand why companies who access the form continuously could have issues with that solution.

**Comment by emagdalenaC2i** [comment]
Both options seem right to me:
- New line on the top
- Move to look like the opportunities form view

**Comment by pedrobaeza** [comment]
@astirpe the issue is that it moves all the rest of the content to bottom with a lot of wasted empty space, forcing you to scroll more on small devices than having all in one line. A similar question will decide us to discard this module: https://github.com/OCA/web/tree/11.0/web_searchbar_full_width for all our customers.

**Comment by astirpe** [comment]
@pedrobaeza I took two screenshots from Runbot:

Inline (this PR):
image

Separate line (the other PR):
image

I cannot see differences in space wasted between the two PRs.

**Comment by astirpe** [comment]
My  https://github.com/OCA/project/pull/532#issuecomment-489045437 is wrong: the "In Progress/Blocked" widget seems totally to the right in any case.

**Comment by pedrobaeza** [comment]
OK, I see the smart-button prevents extra space. Sorry for the noise. It's OK for me then.

**Pull request closed without merging**
