### PR TITLE
Activate module unit tests

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:

**Comment by dreispt** [comment]
Is failing because an error was found testing `project_issue_baseuser`.
Initial analysis points at domains using the removed `state` field: https://travis-ci.org/dreispt/project-service/jobs/35581755#L1392
Will investigate further.

**Comment by dreispt** [comment]
I rebased this on top of #26 (and #25) to confirm if the problem is solved, and all looks good now.

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
