### PR TITLE
[11.0][IMP] project_timeline: Task timeline template

### PR DESCRIPTION
**Pull request by tarteo**
This needs:

- [x] https://github.com/OCA/web/pull/996
- [x] https://github.com/OCA/web/pull/1003

The project task timeline will look like:

image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It would be great to have planned hours also on the view, and maybe the progress bar

**Comment by pedrobaeza** [comment]
You can rebuild now for having the other PR included

**Comment by tarteo** [comment]
@pedrobaeza I've added the progress bar but to format the planned hours like a float_time widget I need to  make some changes to web_timeline to include like web.field_utils in the rendering of the qweb template or do it before the render.

**Comment by tarteo** [comment]
@pedrobaeza Removed the progress bar because otherwise the module needs a dependency to hr_timesheet.

**Comment by pedrobaeza** [comment]
Ok, we can put a new module with that dependency. About the planned hours, I still consider very important to have it on this view, so the modification on web_timeline is welcome

**Comment by caiuka** [comment]
I agree, it would be a great improvement

**Comment by tarteo** [comment]
@pedrobaeza Here you go.

**Comment by tarteo** [comment]
The progress bar https://github.com/OCA/project/pull/411 (like in https://github.com/OCA/web/pull/996)

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Great work!

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
