### PR TITLE
[16.0][FIX]project_key: Fixed Installation of module on fresh database with demo data.

### LINKED ISSUE #1274: 16.0 project_key installation issue
step to reproduce: 
create a fresh database with demo data and try to install module. you will get the below error.

image

### PR DESCRIPTION
**Pull request by ssoni-surekhatech**
Fixed the issue that occurred while installing on demo data.

### CODE REVIEW

**Review by ng-ife — APPROVED** [review]

**Review by hspl-vegra — APPROVED** [review]

**Comment by hspl-vegra** [comment]
https://github.com/OCA/project/issues/1274 This issue is fixed in this pr. 
LGTM

**Review by hspl-rovir — APPROVED** [review]

**Review by hspl-heetz — APPROVED** [review]

**Comment by hspl-vegra** [comment]
@dreispt is there any chance to merge this ?
Thanks in advance

**Comment by ho-ife** [comment]
Hello @pedrobaeza 

can you help here?

Best regards
Henning

**Pull request merged**
