### PR TITLE
9.0 mig project_issue_department

### PR DESCRIPTION
**Pull request by thinkwelltwd**
The #173 PR hasn't been merged yet, but I need the module for v10. Hope you can use this PR for that.

### CODE REVIEW

**Comment by dreispt** [comment]
Travis is red.

**Comment by thinkwelltwd** [comment]
Travis complains that...
>UserError: (u"You try to install module 'project_issue_department' that depends on module 'project_department'.\nBut the latter module is not available in your system.", None)

`project_department` is ported on the 9.0 branch, so I don't know what to do.

**Comment by dreispt** [comment]
@thinkwelltwd It was an old build, probably made before project_department was merged.
I restarted it: https://travis-ci.org/OCA/project/builds/223165452

**Comment by thinkwelltwd** [comment]
> @thinkwelltwd It was an old build, probably made before project_department was merged.

It's still borking on the same error. I despair of ever getting tests to pass. The test system is quite annoying.

**Comment by dreispt** [comment]
@thinkwelltwd Actual tests are OK. You just have one lint issue to fix: https://travis-ci.org/OCA/project/jobs/243280836#L542

**Comment by thinkwelltwd** [comment]
> You just have one lint issue to fix:

It is now fixed. the ole nemesis `project_department` is still throwing the hissy fit. What's the recommended workflow to accomplish all this and actually close this very minor PR?

**Pull request closed without merging**
