### PR TITLE
[12.0][MIG] project_task_add_very_high

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by emagdalenaC2i — APPROVED** [review]
Code review and test on runbot

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Review by pedrobaeza — APPROVED** [review]
Except for the squashing.

**Comment by astirpe** [comment]
Thanks. I also would like to add a maturity level "Stable" for this simple module. Is it okay?

**Comment by pedrobaeza** [comment]
Yes, perfect. You can add you as maintainer also, and pre-generate the README for seeing everything correct now.

**Comment by astirpe** [comment]
Manifest updated + commits squashed

**Comment by tafaRU** [comment]
@astirpe, I think @pedrobaeza means https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L14

**Comment by astirpe** [comment]
@tafaRU https://github.com/OCA/project/pull/441/files#diff-2963425a3306061d9f4812a29e37924eR10
I squashed the commit with the global migration one.

**Comment by tafaRU** [comment]
@astirpe, ok then! I only checked https://github.com/OCA/project/pull/441/commits/7d744b4534b83b522f789a208dfe87da71a37930 :wink:

**Comment by astirpe** [comment]
Commit regarding the readme also squashed now :+1:

**Review by tafaRU — APPROVED** [review]
BTW, it's nice to see the maintainer avatar in the README file! Cool feature :metal: 
https://github.com/onesteinbv/project/blob/12_mig_project_task_add_very_high/project_task_add_very_high/README.rst

project readme rst at 12_mig_project_task_add_very_high onesteinbv project

**Review by tarteo — APPROVED** [review]

**Pull request merged**
