### PR TITLE
[14.0] [MIG] project_timeline

### PR DESCRIPTION
**Pull request by ellbristow**
Copy of v13, version update to v14
Fixed edit_project view. Previous xpath no longer exists

### CODE REVIEW

**Comment by ellbristow** [comment]
Pending merge of:
https://github.com/OCA/web/pull/1838

**Review by dreispt — CHANGES_REQUESTED** [review]
Thank you @ellbristow 
The commit history need to be brought over.
To do that, check the git instructions here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by dreispt** [comment]
Superseded by #800

**Review by DavidBForgeFlow — COMMENTED** [review]
As #800 is merged, you can close this PR. I will check your #794.

**Pull request closed without merging**
