### PR TITLE
[IMP] project_task_materials: Migrate to API 8.

### PR DESCRIPTION
**Pull request by sergio-teruel**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Two PEP8 issues:

```
./project_task_materials/__init__.py:3:1: W391 blank line at end of file
./project_task_materials/models/__init__.py:3:1: W391 blank line at end of file
```

I suggest you to put https://github.com/OCA/maintainer-quality-tools/tree/master/git for avoiding waiting to Travis to know if there's something wrong.

**Comment by pedrobaeza** [comment]
:+1: when PEP8 fixes. Tests errors is related to project_sla, not this one.

**Comment by dreispt** [comment]
:+1:

**Comment by rafaelbn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
You need to rebase

**Comment by rafaelbn** [comment]
@dreispt @pedrobaeza I this this is ready to merge, isn't it?

**Pull request merged**
