### PR TITLE
[12.0][MIG] project_wbs_task

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Based on #471

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
cc @ForgeFlow

**Comment by Saran440** [comment]
@AaronHForgeFlow please, use new README by fragment system.

reference : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#tasks-to-do-in-the-migration

**Comment by AaronHForgeFlow** [comment]
@Saran440 done :)

**Comment by Saran440** [comment]
@AaronHForgeFlow 
I clicked icon Tasks in WBS menu but it's error.
Selection_005

I don't know how to setting something in task?
Can you explain in readme?
Thank you. :)

**Comment by AaronHForgeFlow** [comment]
> @AaronHForgeFlow
> I clicked icon Tasks in WBS menu but it's error.
> Selection_005
> 
> I don't know how to setting something in task?
> Can you explain in readme?
> Thank you. :)

My bad, I will remove view type gantt, that was for enterprise version

**Review by Saran440 — APPROVED** [review]
Functional Test :+1: 

@AaronHForgeFlow Can enterprise version use this module?

**Comment by AaronHForgeFlow** [comment]
Just squashed and rebased.

> @AaronHForgeFlow Can enterprise version use this module?

Sure, there is no incompatibility in models neither in views. Thanks for reviewing.

**Comment by AaronHForgeFlow** [comment]
`Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click_odoo/env_options.py", line 214, in _invoke
    return self.org_invoke(ctx)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click_odoo_contrib/makepot.py", line 122, in main
    commit_message,
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click_odoo_contrib/makepot.py", line 70, in export_pot
    raise click.ClickException("%d invalid .po file(s) found" % invalid_po)
click.exceptions.ClickException: 1 invalid .po file(s) found
Error: 1 invalid .po file(s) found`

No idea about the fix :confused:

**Comment by alexey-pelykh** [comment]
@AaronHForgeFlow see
```
./project_wbs_task/i18n/zh_CN.po:1:2: syntax error
```
I'd remove file, yet I suspect that there's an issue with one of messages, so it will be ok just removing it

**Comment by alexey-pelykh** [comment]
On other hand, it's only on odoo, not OCB, maybe they've broken/fixed something odd?

**Pull request merged**
