### PR TITLE
[11.0][IMP] project_category: Project type in task and parent types

### PR DESCRIPTION
**Pull request by tarteo**
**Added:**

- Use project_type also for tasks
- Parent types

**Updated:**

- Form for project_type it looks now like this:

image

### CODE REVIEW

**Comment by ovnicraft** [comment]
@tarteo any updates for this ?

**Comment by tarteo** [comment]
@ovnicraft I don't understand you. What do you mean?

**Comment by ovnicraft** [comment]
@tarteo LGTM wait for another review.

**Review by LoisRForgeFlow — APPROVED** [review]
Tested on runbot :+1:

**Review by emagdalenaC2i — APPROVED** [review]
Code review and tested in runbot

**Review by pedrobaeza — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Just one question - what was the value of mixing project and task categories instead of introducing `project_task_category` separately? Even if that would have been using same categories as in project. Not quite modular?

**Pull request merged**
