### PR TITLE
[16.0][MIG] project_task_material: migration to 16

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes https://github.com/OCA/project/pull/1139

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by ValentinVinagre** [comment]
@rousseldenis what do you think? it's all okay?

**Review by HaraldPanten — APPROVED** [review]

**Comment by ValentinVinagre** [comment]
@rousseldenis it's ready to merge?

**Review by NICO-SOLUTIONS — COMMENTED** [review]
Functional review. LGTM

**Comment by HaraldPanten** [comment]
@rousseldenis @pedrobaeza @etobella do you mind merging this one?

THX

**Comment by pedrobaeza** [comment]
Can you please squash these commits for reducing noise?:

Selección_012

I recommend you to use `project_stock` as a better alternative.

**Comment by ValentinVinagre** [comment]
> Can you please squash these commits for reducing noise?:
> 
> Selección_012
> 
> I recommend you to use `project_stock` as a better alternative.

We will do the squahs and we will review the other module, thank you very much for the comments :)

**Pull request merged**
