### PR TITLE
[IMP] project_role: inherit create in batch

### PR DESCRIPTION
**Pull request by len-foss**

### CODE REVIEW

**Review by SkiBY — APPROVED** [review]

**Review by astirpe — APPROVED** [review]
Thank you for this PR! The fix looks good.

I just want to propose two minor improvements, but they are not blocking, so I approve already.

1. I would rename `_fill_create_assignment_values()` to something more specific for this module, something like: `_project_role_create_assignment_values()`
2. For improving performance, I would move the `browse(values["company_id"])` from inside the method to outside, so that the browse will retrieve all the companies (eg.: `companies = ... .browse(values["company_ids"])`) and then inside the method just filter to get the correct company (eg.: `company = companies.filtered(lambda c: c.id == values["company_id"])`)

**Comment by len-foss** [comment]
@astirpe Thank you, I updated it in that sense since both remarks make good sense. I don't think the method is much more difficult to override this way so it should be fine.

**Comment by astirpe** [comment]
Can this one be merged?

**Comment by auroraeosrose** [comment]
I'm also waiting on this - looks good to me!

**Comment by ramiadavid** [comment]
@dreispt Looks like it hasn't been merged

**Pull request merged**
