### PR TITLE
[16.0][IMP] project_stock_product_set: Adapt wizard to changes in product_set

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
Pending from:

- [x] https://github.com/OCA/product-attribute/pull/1548

Moved some of the logic shared by the wizard defined in the module sale_product_set to the module product_set so the dependency of project_stock_product_set should now be on product_set.

cc @Tecnativa

@pedrobaeza @victoralmau please review

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
In `add_set`, call always super, and don't add the `self.check_partner()` call.

**Comment by pilarvargas-tecnativa** [comment]
> In `add_set`, call always super, and don't add the `self.check_partner()` call.

:+1:  thanks

**Review by victoralmau — CHANGES_REQUESTED** [review]
Remember to only take into account product type lines (avoid sections for example).

**Comment by pilarvargas-tecnativa** [comment]
> Remember to only take into account product type lines (avoid sections for example).

True, this was not taken into account before, it is already included in this module as well, thanks for reminding me.

**Review by victoralmau — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Pull request merged**
