### PR TITLE
[12.0][UPD] project_wbs: add migration scripts to v12

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fast-track.

No need to increase the number version when merge!

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@mreficent won't `oldname` do a better job?

**Comment by MiquelRForgeFlow** [comment]
No, `oldname` does an awful job. That's why `rename_fields` method exists and that's why `oldname` is removed in v13.

**Comment by alexey-pelykh** [comment]
Sounds reasonable 👍

**Pull request merged**
