### PR TITLE
[12.0][IMP]project_parent_task_filter-Add-group

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by ovnicraft** [comment]
LGTM

**Comment by emagdalenaC2i** [comment]
@nikul-serpentcs @tarteo and @pedrobaeza Could you review this PR?

**Review by nikul-serpentcs — APPROVED** [review]
Code Review LGTM :+1:

**Comment by emagdalenaC2i** [comment]
@ovnicraft if you have review the code and tested, then please mark it as approved

**Comment by ovnicraft** [comment]
I am not able to do it, @pedrobaeza can you help me ?

**Comment by pedrobaeza** [comment]
@ovnicraft check this image for how to do it:

imagen

**Review by ovnicraft — APPROVED** [review]

**Comment by ovnicraft** [comment]
@pedrobaeza my issue, thank you !

**Pull request merged**
