### PR TITLE
[IMP] project_timeline: scss instead of less

### PR DESCRIPTION
**Pull request by sbidoul**
`lessc` is not a mandatory dependency of Odoo 12, so let's use scss instead.

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Comment by pedrobaeza** [comment]
You can't do this change without switching syntax

**Comment by sbidoul** [comment]
@pedrobaeza what should I change exactly? This file looks like regular css to me.

**Comment by pedrobaeza** [comment]
OK, if there's no variable, then call it simply css, not scss, but it's weird that it's called previously less without having less variables.

**Comment by sbidoul** [comment]
I don't know. Looks like a tradition to name these files scss everywhere. Admitedly I've no idea what I'm doing here :)

**Comment by pedrobaeza** [comment]
Indeed the file contains plain CSS, so I still think it should be called `.css`

**Comment by pedrobaeza** [comment]
Let's invoke @Yajo that knows about this stuff.

**Review by yajo — APPROVED** [review]
The fix is OK, in this case it's only using syntax that is shared between Less and Scss.

BTW the file is not valid CSS! It seems you guys are so used to Less/Scss that can't distinguish it from CSS now... :yum: This is the CSS it produces when compiled:

```css
.o_project_timeline_item small[name='planned_hours'] {
  font-size: 85%;
}
```

**Comment by pedrobaeza** [comment]
And isn't better then to put the plain CSS and avoid any compilation?

**Comment by yajo** [comment]
No, let the Scss. It's more maintainable and readable. I doubt you're gonna save 1ms.

**Comment by pedrobaeza** [comment]
Thanks for the clarifications, @Yajo, and thanks @sbidoul for proposing this improvement. Merging!

**Pull request merged**
