### PR TITLE
[15.0][MIG] project_milestone

### PR DESCRIPTION
**Pull request by Mantux11**
For now one, odoo has their own milestone's. So only we need migration to this module, to save information. There is new module called `project_task_milestone`. There is PR #888. We need that to link `project.task` with `project.milestone`.

### CODE REVIEW

**Comment by tarbib** [comment]
@Mantux11 thanks for this.
Sad to see that in Odoo standard v15 we lose the possibility to assign a milestone to a task :(

**Review by gurneyalex — APPROVED** [review]

**Comment by Mantux11** [comment]
@davejames Also here. Tests failing because of `project_task_milestone` dependency.

**Review by Du-ma — APPROVED** [review]

**Review by gaikaz — APPROVED** [review]

**Comment by gaikaz** [comment]
@OCA/project-service-maintainers 
This is getting a little stale. Could we please push it somewhat?
Thanks.

**Comment by alexey-pelykh** [comment]
@gaikaz shouldn't test be green to push this forward?

**Comment by gaikaz** [comment]
@alexey-pelykh 
Hi! Yeah, I guess you are right. They fail here because this module is sort of a "dummy" in v15 just so you can do migration. 
It actually is being renamed/refactored in another PR: https://github.com/OCA/project/pull/888
And there's now a dependency added here. Hence, the tests failing.
If you could get that other PR merged, this one would then pass.

**Comment by Mantux11** [comment]
@alexey-pelykh Rebased from 15, all test's are green now, If you could review that and merge, it would be awesome. Thanks a lot :)

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@Mantux11 the last request is to amend the commit message to match the guidelines and I'll happily merge it

**Comment by Mantux11** [comment]
@alexey-pelykh Do you mean, that commit message must be [MIG] project_milestone: Migration to 15.0?

**Comment by alexey-pelykh** [comment]
@Mantux11 yes, as per https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by Mantux11** [comment]
@alexey-pelykh Okey, I have renamed the commit message.

**Pull request merged**
