### PR TITLE
Fix README buttons

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please add also Coveralls badge.

Do you want also to include Transifex?

**Comment by dreispt** [comment]
Added.

**Comment by pedrobaeza** [comment]
Coveralls  badge is not yet present. Can you add it?

**Comment by dreispt** [comment]
Coverage status is there!

**Comment by tafaRU** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Sorry, runbot is the missing one

Can you check the error in CIs

**Comment by dreispt** [comment]
Got it, added. CI errors are unrelated to this change.

**Comment by pedrobaeza** [comment]
But it's due the change in dependencies handle. Can you please fix it at the same time? (https://github.com/OCA/project/blob/7.0/.travis.yml#L27)

**Comment by dreispt** [comment]
Fixed.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by dreispt** [comment]
Merge please.

**Comment by pedrobaeza** [comment]
CIs errors are unrelated, so I merge.

**Pull request merged**
