### PR TITLE
[14.0] [MIG] Project_tag

### PR DESCRIPTION
**Pull request by Yoshiro009**
Standard  Migration

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Comment by tonygalmiche** [comment]
you can also add:
` options="{'color_field': 'color'}"`

on project.tags.tree:

image

**Review by skeller1 — APPROVED** [review]

**Review by patrickrwilson — APPROVED** [review]
Can you squash your commits?

LGTM

**Comment by newtratip** [comment]
@tonygalmiche, done
Selection_160

**Review by marcelsavegnago — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
