### PR TITLE
[10.0][MIG] sale_order_project

### PR DESCRIPTION
**Pull request by Abranes**
Migration of the module `sale_order_project` to `10.0`.

We remove the field `related_project_id` because now it's present in `sale` base module.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this really needed with current v10 possibilities about products that creates tasks?

**Comment by Abranes** [comment]
That's true it's not really needed with v10. But if you want to create a related empty project and after create your tasks by hand this module is useful. (That is the use case of one of our customers)

**Comment by pedrobaeza** [comment]
OK, a requirement a bit weird, but I have seen worse, hehe.

Check Travis.

**Comment by Abranes** [comment]
Travis is complaining about project_closing tests. sale_order_project tests are OK.

**Comment by pedrobaeza** [comment]
But main branch is green, so it should be your module that is breaking the other one.

**Comment by astirpe** [comment]
Rebase the branch. The Travis failure should be fixed now.

**Review by acsonefho — CHANGES_REQUESTED** [review]
Hello, I think that you should check into the action_create_project (in sale.order) that a project_id is not already set for the sale order (and raise an exception if it's the case).
We can't fully trust a button. If there is an issue with a button (or if someone add it somewhere else without the invisible attribute).

**Pull request closed without merging**
