### PR TITLE
[14.0][MIG] project_template_milestone

### PR DESCRIPTION
**Pull request by Chanakya-OSI**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Chanakya-OSI can you squash the automated commits in history (all the translation, .pot, upd)?

**Comment by Freni-OSI** [comment]
> @Chanakya-OSI can you squash the automated commits in history (all the translation, .pot, upd)?

Done. ready for review

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
