### PR TITLE
[14.0] [MIG] project_timeline_hr_timesheet copied from 13.0 to 14.0

### PR DESCRIPTION
**Pull request by ellbristow**
Straight copy of v13 with version iterated to v14

### CODE REVIEW

**Comment by ellbristow** [comment]
Pending acceptance of project_timeline merge:
https://github.com/OCA/project/pull/795

**Comment by fshah-initos** [comment]
Hi @ellbristow 
Please follow oca guideline for migration 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by DavidBForgeFlow** [comment]
Tested on runbot. In the tasks view, the timeline view, which this module should incorporate, is not appearing. Could you check?
image

**Comment by MiquelRForgeFlow** [comment]
@ellbristow are you still active with this PR? please, could you attend comments and rebase?

**Comment by ellbristow** [comment]
Sorry. This should have been closed. The port didn't work as expected

**Pull request closed without merging**
