### PR TITLE
[16.0][FIX] project_task_default_stage: Add group on task stages page

### PR DESCRIPTION
**Pull request by ByteMeAsap**
Adds Technical/Features group on Task stages(named as Project Stages) page on Project Form View.The same group is applied on Task Stages Menu under Project Configuration menu in project module

### CODE REVIEW

**Review by flotho — APPROVED** [review]
Tested on runboat, 
do what's described
LGTM
Thanks

**Comment by coleste** [comment]
LGTM

**Review by coleste — APPROVED** [review]

**Comment by ByteMeAsap** [comment]
@pedrobaeza , can we have this merged?

**Comment by pedrobaeza** [comment]
OK, although my recommendation is to put "Technical features" to everyone using `base_technical_features`. It will save you a lot of tickets saying "I can't change this", or "I don't see this".

/ocabot merge patch

**Pull request merged**
