### PR TITLE
[12.0] [MIG] project_category

### PR DESCRIPTION
**Pull request by Nikul-Chaudhary**
Project Types
=============
* This module adds the category type fields in project.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We should wait with this one until #463 is merged for including it here.

**Comment by Nikul-Chaudhary** [comment]
> We should wait with this one until #463 is merged for including it here.

Yes @pedrobaeza, If it's Done then I will start my work, and rebase. Don't worry!

**Comment by emagdalenaC2i** [comment]
@pedrobaeza can you review #463 that is already approved, so @Nikul-Chaudhary can improve and rebase this PR?

**Comment by pedrobaeza** [comment]
Yes I was just with it. Merged, but it's not a rebase, but cherry-picking the commit.

**Comment by Nikul-Chaudhary** [comment]
@pedrobaeza @emagdalenaC2i Now Done, cherry-picked all commits from https://github.com/OCA/project/pull/463 PR.

**Review by pedrobaeza — APPROVED** [review]

**Review by emagdalenaC2i — APPROVED** [review]
Code review and tested in Runbot

**Comment by emagdalenaC2i** [comment]
@pedrobaeza could you merge this PR?

**Pull request merged**
