### PR TITLE
Added spanish translation for project_status

### PR DESCRIPTION
**Pull request by estekadigital**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use Weblate for doing translations:

https://odoo-community.org/page/translate

**Comment by estekadigital** [comment]
Thanks @pedrobaeza , I am trying to update the translations but it says I do not have enough permission to save or suggest.. I am new to weblate, do i need to ask for permission to edit or fork the translations ?

**Comment by pedrobaeza** [comment]
Well, the link I put contained the instructions. I have put to `estekadigital` Spanish translator role.

**Comment by estekadigital** [comment]
Thanks @pedrobaeza

**Pull request closed without merging**
