### PR TITLE
[16.0] [MIG] project_parent_task_filter

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by leemannd** [comment]
Hello @emagdalenaC2i Thank you for the work. The pre-commit is failing. The base configuration has been updated into the branch 16.0 . Could you rebase on the branch 16.0 ?

**Comment by emagdalenaC2i** [comment]
@leemannd done

**Review by leemannd — APPROVED** [review]
Thank you.
Last change request, could you please merge togheter your last two commits?
They have the same message and purpose (migration)

**Comment by emagdalenaC2i** [comment]
@leemannd done

**Pull request merged**
