### PR TITLE
[14.0][ADD] sale_project_service_tracking_copy_tasks

### PR DESCRIPTION
**Pull request by EmilioPascual**
This module add the possibility to create task in an existing project from the sales order through setting the product with a project template with the desired task.

@moduon MT-1028

@Shide, @rafaelbn please review

### CODE REVIEW

**Review by Shide — APPROVED** [review]
**praise:** Thanks for porting the module <3

**todo (non-blocking):** fix pre-commit

LGTM

**Comment by EmilioPascual** [comment]
Fix pre-commit: https://github.com/OCA/project/pull/1187

**Review by rafaelbn — APPROVED** [review]
Well, over 1-year in production...

👍🏼

**Comment by EmilioPascual** [comment]
@rafaelbn or @yajo can you merge?

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
