### PR TITLE
[FIX] account_analytic_analysis_recurring: #START# and #END# set correctly

### PR DESCRIPTION
**Pull request by pedrobaeza**
[IMP] Some conventions
[IMP] Copy method

### CODE REVIEW

**Comment by dreispt** [comment]
Since you're returning at this, maybe you could also fix the security ACL issue: permissions are given to Project groups that are not required by the module's dependencies.

**Comment by dreispt** [comment]
Despite my comment above, I see no reason not to merge this :+1:

**Comment by pedrobaeza** [comment]
I have fixed permissions also, @dreispt :)

**Comment by dreispt** [comment]
Great Pedro! :+1:

**Pull request merged**
