### PR TITLE
[FIX] remove broken symbolic links;

### PR DESCRIPTION
**Pull request by legalsylvain**
remove 4 broken symbolic links that were maybe working in launchpad time.

### CODE REVIEW

**Comment by bealdav** [comment]
:+1:

**Comment by florian-dacosta** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by bguillot** [comment]
:+1:

**Comment by elicoidal** [comment]
should I merge without travis?

**Comment by dreispt** [comment]
:+1:

**Comment by pedrobaeza** [comment]
We can merge safely in this case.

**Comment by dreispt** [comment]
Is was typing "no need to rush" but.... :fast_forward:

**Pull request merged**
