### PR TITLE
Backport project_issue_code

### PR DESCRIPTION
**Pull request by agb80**

### CODE REVIEW

**Comment by agb80** [comment]
Both errors not related with this module

Travis:

```
2016-03-10 16:32:14,226 23716 ERROR openerp_test openerp.tools.convert: Parse error in /home/travis/build/OCA/project/analytic_hours_block/hours_block_data.xml:6:
```

Runbot:

```
(module.name, dep.name,))
except_orm: (u'Error', u"You try to install module 'project_action_item' that depends on module 'hr_timesheet_task'.\nBut the latter module is not available in your system.")
```

**Comment by pedrobaeza** [comment]
Does this still apply? You should fix Travis in another PR and then rebase when merged.

**Comment by dreispt** [comment]
@pedrobaeza For 7.0 I don't mind merging with a red Travis, as long as the module has no errors.

**Comment by pedrobaeza** [comment]
The error is not in the linter, but in tests, so it's needed to be fixed.

**Comment by pedrobaeza** [comment]
Any news on this or should I close it?

**Comment by dreispt** [comment]
Hey @agb80, do you plan to continue this PR?

**Comment by agb80** [comment]
yes, sorry for not being able to answer, there are to much work this days here. As soon as I can take some time off I will check the test

**Comment by dreispt** [comment]
@agb80 OK, no problem.

**Comment by dreispt** [comment]
I'm closing this for inactivity.
You're welcome to repopen it.

**Pull request closed without merging**
