### PR TITLE
Update tr.po

### PR DESCRIPTION
**Pull request by SalahAdDin**
I could not fınd the way to being added to the `transifex` team.

### CODE REVIEW

**Comment by tarteo** [comment]
OCA switched from transifex to Weblate. I don't know if Transifex is still active on this repository.
https://odoo-community.org/blog/our-blog-1/post/translations-platform-81#scrollTop=0
Maybe try to suggest the translations at Weblate.

**Comment by SalahAdDin** [comment]
Well, how can i suggest that translations at Weblate?

**Comment by tarteo** [comment]
@SalahAdDin Register, login, find the translation, and apply your translations.

**Comment by SalahAdDin** [comment]
Ok, but, is it possible to merge these translations?

I'm trying to make translations there but it seems as I have no permissions.

**Comment by pedrobaeza** [comment]
I'm going to merge this time the translation, but please use Weblate next time.

**Comment by pedrobaeza** [comment]
On Weblate, you don't have permissions for merging as it's an automatic process.

**Pull request merged**
