### PR TITLE
[14.0][IMP] project_tag: added 'Tags Required' field

### PR DESCRIPTION
**Pull request by AshishHirapara**
PR to add the 'Tags Required' field to project

### CODE REVIEW

**Review by leemannd — CHANGES_REQUESTED** [review]
I don't understand why the tags are removed on the project

**Comment by AshishHirapara** [comment]
> I don't understand why the tags are removed on the project
@leemannd, it was a misunderstanding on my part. I have reverted it.

**Review by francesco-ooops — APPROVED** [review]
functional review ok

these changes mirror the same implemented for milestone here #947 

@leemannd can you take a look again? thanks!

**Review by leemannd — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/project-service-maintainers can this be merged?

**Comment by simahawk** [comment]
@leemannd next time, please, use `merge minor` as we have a minor change here :pray:

**Comment by leemannd** [comment]
Ouch mistake on my side. Thank you for the reminder.

**Pull request merged**
