### PR TITLE
forward-port v9 of project_task_delegate

### PR DESCRIPTION
**Pull request by ghost**
the new PR

### CODE REVIEW

**Comment by ghost** [comment]
Why now two checks fail?

**Comment by rafaelbn** [comment]
Hi @kkinateder , thanks for this contribution. Please read and follow guidelines https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md and for new modules use the OCA template: https://github.com/OCA/maintainer-tools/tree/master/template/module
Thanks

**Comment by dreispt** [comment]
Only the lint check is failing: https://travis-ci.org/OCA/project/jobs/146121267#L447

**Comment by dreispt** [comment]
@kkinateder This PR involves two modules. You should do one PR per module.

**Pull request closed without merging**
