### PR TITLE
[12.0] [MIG] project_timeline_critical_path

### PR DESCRIPTION
**Pull request by anandkansagra**
Issue [Reference](https://github.com/OCA/project/issues/435)

### CODE REVIEW

**Review by astirpe — CHANGES_REQUESTED** [review]
Would be nice if you can also fix the javascript warnings in the Travis lint: https://travis-ci.org/OCA/project/jobs/532126530#L637

**Comment by astirpe** [comment]
Runbot is failing. Please rebase the branch.

**Comment by anandkansagra** [comment]
> Runbot is failing. Please rebase the branch.

Runbot is green now...

**Comment by nrome-n** [comment]
Hi not sure if this is the right location.
I am geting 
this.get_critical_paths(events).done is not a function
then using the project_timeline_critical_path

**Pull request closed without merging**
