### PR TITLE
[15.0][ADD] project_task_description_template: new module

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

New module to manage description templates for  project tasks

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by ygol** [comment]
getting error on runbot when calling a template in a task.
```
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 921, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1324, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 6486, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoo/models.py", line 6219, in _onchange_eval
    method_res = method(self)
  File "/mnt/data/odoo-addons-dir/project_task_description_template/models/project_task.py", line 15, in _onchange_description_template_id
    self.description += self.description_template_id.description
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: unsupported operand type(s) for +=: 'bool' and 'Markup'
```

**Comment by alan196** [comment]
@ygol Thanks for the review! I just fixed the issue.

Could you help me to review again. 🙏

**Comment by alan196** [comment]
@EduardoJarsa Could you help me to review this PR 🙏

**Review by EduardoJarsa — APPROVED** [review]
Functional review, everything looks working

**Review by ygol — APPROVED** [review]
LGTM

**Comment by alan196** [comment]
@OCA/project-service-maintainers Could you help me to review or merge this PR 🙏

**Pull request merged**
