### PR TITLE
[12.0][IMP] project_timeline - Enable subtasks

### LINKED ISSUE #485: [IMP] project_timeline: Timeline view & Subtasks
Currently, the timeline view does not distinguish tasks and subtasks. 
It would be nice to have a filter to show only the parent tasks (without subtasks), as defined in #347 

Also, when accessing the subtasks of a specific task, the timeline view is not available.

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
Fixes #485

### CODE REVIEW

**Comment by tarteo** [comment]
Can you rebase please for the scss fix?

**Comment by emagdalenaC2i** [comment]
@tarteo rebased ready

**Comment by tarteo** [comment]
@emagdalenaC2i I still get the error in Runbot:

image

But in the code I see you're only adding an action. Don't you need a menu item too?

**Comment by emagdalenaC2i** [comment]
I think I didn't rebase it properly and the scss error is still there

I will check it later

**Comment by emagdalenaC2i** [comment]
Closed, see #498

**Pull request closed without merging**
