### PR TITLE
[13.0][MIG] project_task_add_very_high

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by emagdalenaC2i — APPROVED** [review]
Tested and code review

**Comment by emagdalenaC2i** [comment]
@tafaRU @tarteo and @pedrobaeza Please, could you review this PR?

**Review by tarteo — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
Please rebase and adapt this to black

**Comment by astirpe** [comment]
@pedrobaeza Done!

**Pull request merged**
