### PR TITLE
[12.0][IMP] Don't allow create-and-edit on assignments

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Roles should be created in a separate menu, Create-and-Edit turns out to be very error-prone

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza if possible, take a look if I've used `options` correctly

**Comment by pedrobaeza** [comment]
It seems correct.

**Comment by alexey-pelykh** [comment]
awesome! @mreficent @aheficent @Nikul-Chaudhary summoning all of you for reviews, please :)

**Review by nishaodedra — APPROVED** [review]
LGTM

**Review by emagdalenaC2i — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Related #490

**Pull request merged**
