### PR TITLE
Extend state and fold statusbar to Issues

### PR DESCRIPTION
**Pull request by dreispt**
- Extends Project Stage State to Project Issues
-  Adds a "Folded on Statusbar" flag, to pick the Stages visible on Tasks and Issue statubars (header pipeline).

:warning:  Depends on #75 (MERGED)

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1: 
Don't you want to update both README.md with OCA template?

**Comment by jgrandguillaume** [comment]
Hi,

Thanks for the contrib !

I'm giving my :+1:

**Comment by dreispt** [comment]
Merge please!

**Comment by yvaucher** [comment]
Done

**Comment by dreispt** [comment]
Thanks!

**Pull request merged**
