### PR TITLE
[17.0][MIG] project_task_stage_state: Migration to 17.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 17.0

Please @pedrobaeza and @carlos-lopez-tecnativa can you review it?

Related to https://github.com/OCA/timesheet/pull/721#pullrequestreview-2427684428

@Tecnativa TT51692

### CODE REVIEW

**Review by carlos-lopez-tecnativa — APPROVED** [review]
LGTM, thanks!

**Review by zamberjo — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
Change the word `status` by `state`, and the rest seems OK.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
