### PR TITLE
11.0 [FIX]  project_task_material_stock - Stock move stays in Assigned State after click on consume material button

### PR DESCRIPTION
**Pull request by jcarlosmontoya**
Stock move stays in Assigned State after click on consume material button
This PR FIX problem and set quantity_done before to call action_done method (Like a Inventory Adjustments)

### CODE REVIEW

**Comment by jcarlosmontoya** [comment]
Hello Everyone, any problem with the implementation, do not hesitate to comment and we solve it
Best regards ;)

**Comment by jcarlosmontoya** [comment]
Does have any problem if you set quantity_done directly on stock move instead create move_line_ids in this particular case?
Check this example when create an Inventory Adjustment:
https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_inventory.py#L430

**Comment by jcarlosmontoya** [comment]
:+1: I just test in Runbot

image

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Comment by nikul-serpentcs** [comment]
@jcarlosmontoya `Travis` still Fail

**Review by cubells — CHANGES_REQUESTED** [review]
@jcarlosmontoya 
can you increase module version to `11.0.1.0.1`?

**Comment by jcarlosmontoya** [comment]
@cubells sure, thanks

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Comment by cubells** [comment]
thanks!

**Review by nikul-serpentcs — APPROVED** [review]
LGTM :+1:

**Comment by jcarlosmontoya** [comment]
Thank you everyone 👍🏼

**Pull request merged**
