### PR TITLE
Migrado a Odoo 11

### PR DESCRIPTION
**Pull request by dsasoftware**
Se realizaron los ajustes necesarios para que funcione en Odoo 11

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis status.

**Comment by dsasoftware** [comment]
Hola!
Muy buenos días
Un cliente que me solicito la actualización del modulo, me indico que quería subirlo al repositorio. Lo coloco para que sea revisado.
No tengo conocimiento de que hacer con los "2 failing checks"

**Comment by AaronHForgeFlow** [comment]
Thank you for your collaboration. Please include the module name in the title of the Pull Request.

**Comment by pedrobaeza** [comment]
Speak only in English.

If the checks fail, that's because the module is not correctly migrated. You haven't even respected commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0. So as is, I'm afraid this contribution doesn't serve.

**Comment by dsasoftware** [comment]
Lo tendré en cuenta para otra oportunidad.
y es cierto, no use commit, lo cargo directamente.
Aprecio tus respuestas



________________________________
De: Pedro M. Baeza <notifications@github.com>
Enviado: jueves, 7 de junio de 2018 12:22:56 p.m.
Para: OCA/project
Cc: Jonathan Guacaran; Author
Asunto: Re: [OCA/project] Migrado a Odoo 11 (#390)


Speak only in English.

If the checks fail, that's because the module is not correctly migrated. You haven't even respected commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0. So as is, I'm afraid this contribution doesn't serve.

**Comment by MiquelRForgeFlow** [comment]
Thank you for your contribution @dsasoftware, but if this PR is not adapted to [OCA Guidelines (and some RULES)](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md), it will be a waste.

**Comment by pedrobaeza** [comment]
Closing as outdated and failing.

**Pull request closed without merging**
