### PR TITLE
[15.0][MIG][project_task_stage_state] Standard migration to project_task_stage_state

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Comment by HaraldPanten** [comment]
@rafaelbn

**Comment by rafaelbn** [comment]
I thinks this module should be renamed to `project_task_stage_state` as now in v15 we have both project stages and project task stages. Readme should be re-writed to the new logic and menus

imagen

Furthermore, take care of the fact that Odoo remove the "closed" concept and make folded = closed: https://github.com/odoo/odoo/commit/f4c054e4731270a5103ec1d5a97c2789aef977e3#diff-dcdc6e8a2e65aff0582c53d72c3890c1b56725a8b9fcf7abbb0378097b5999afL965-R962

Ping @dreispt

**Comment by HaraldPanten** [comment]
I agree, project_task_stage_state suits better.

Let's wait for other opinions before applying changes.

**Comment by dreispt** [comment]
I’m OK with the change.

--dr

**Comment by manuelregidor** [comment]
@rafaelbn Why should I take into consideration the change in Odoo regarding the fold attribute? Thank you.

**Comment by rafaelbn** [comment]
> Why should I take into consideration the change in Odoo regarding the fold attribute? Thank you.

Hello @manuelregidor , you don't have to 😄 . I just inform you just in case you don't know it.

In this case, just the module name

**Comment by manuelregidor** [comment]
> > Why should I take into consideration the change in Odoo regarding the fold attribute? Thank you.
> 
> Hello @manuelregidor , you don't have to smile . I just inform you just in case you don't know it.
> 
> In this case, just the module name

@rafaelbn OK then. Thank you!

**Comment by HaraldPanten** [comment]
@rafaelbn @dreispt Could you review/merge?

On the other hand, I'd recommend you to add some changes/comments in the migration issue for considering these changes in V16 👍 

THX!

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by rafaelbn — APPROVED** [review]
@dreispt ? 😄 👍

**Comment by dreispt** [comment]
This looks great, but shouldn't it have a migration script?

**Comment by manuelregidor** [comment]
> This looks great, but shouldn't it have a migration script?

Hi @dreispt What do you think the migration script should do? I could add it to the PR. Thank you.

**Comment by dreispt** [comment]
@manuelregidor Maybe no needed if it is only a module name change, with no impact in the actual database.

**Comment by HaraldPanten** [comment]
@dreispt the functionallity is not changing. Just the name. We'll need to include this change to the apriori.py document only.

Could you merge @rafaelbn ?

**Comment by HaraldPanten** [comment]
> @dreispt your merge command was aborted due to failed check(s), which you can inspect on [this commit of 15.0-ocabot-merge-pr-916-by-dreispt-bump-nobump](https://github.com/OCA/project/commits/e19bf0e442a7be59d72f60d662860551309cf594).
> 
> After fixing the problem, you can re-issue a merge command. Please refrain from merging manually as it will most probably make the target branch red.

A temporary issue, maybe?

**Comment by HaraldPanten** [comment]
> /ocabot merge patch

THX!

**Comment by ao-landoo** [comment]
@rafaelbn @HaraldPanten Was this module migrated correcly? Cannot find in on this repo, 15.0 branch

**Comment by rafaelbn** [comment]
https://github.com/OCA/project/tree/15.0/project_task_stage_state

**Pull request merged**
