### PR TITLE
[14.0][IMP] project_timeline: Add planned_date_* fields to the task tree view

### PR DESCRIPTION
**Pull request by victoralmau**
Add planned_date_* fields to the task tree view

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT50618

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Surprised that the daterange widget works in the tree view and without having both fields shown.

**Review by chienandalu — COMMENTED** [review]
No always working as expected:

Errors trying to change the dates:


Here the date range didn't work for the date_end:

timeline-3

And here the date end didn't set the date_start:

Peek 01-10-2024 09-40

This one was ok:


Peek 01-10-2024 09-39

**Comment by victoralmau** [comment]
Changed to show fields without `widget=“daterange”` in tree view because in some cases https://github.com/OCA/project/pull/1345#pullrequestreview-2339368831 it does not work correctly (does not save the value of `planned_date_end`)

**Review by tarteo — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
Great :+1: , better to have a reliable behavior

**Pull request merged**
