### PR TITLE
[16.0][FIX] project_task_parent_filter: Recover create option in "My Tasks" tree view

### PR DESCRIPTION
**Pull request by mariancuadranetkia**
Recover create option in "My tasks" tree view.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for this, Marián. Please follow commit message guidelines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by pedrobaeza** [comment]
@JordiBForgeFlow this was removed by María in c976574aa2a42a32598c30a2cf1753f0ebfb1200. Do you know why?

**Comment by mariancuadranetkia** [comment]
Thanks @pedrobaeza for your answer. Is it recomendable I change commit message and push it again? Or is not necessary?
I'll try to do it better next time.
About views: in kanban view, it's possible create new task but not in tree view (in My tasks). For this, we are not sure about reasons to disable create option and we propose to recover it.

**Comment by pedrobaeza** [comment]
Yes, please reformat the commit message

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by mariancuadranetkia** [comment]
@pedrobaeza I have reformatted the commit message, is it ok? 
Thanks!

**Review by hugomartineznetkia — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
