### PR TITLE
[17.0][IMP] project_type: copy type_id on project/task duplicate

### PR DESCRIPTION
**Pull request by CRogos**
https://github.com/OCA/project/issues/1212

@pedrobaeza what do you think about this change?

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
I don't use it, but it sounds reasonable.

**Comment by CRogos** [comment]
@tobru @francescapenso could you review?

**Comment by tobru** [comment]
Looks good IMHO, thanks

**Comment by CRogos** [comment]
@tobru can you also approve this as review? 
image

**Review by tobru — APPROVED** [review]

**Comment by tobru** [comment]
Could you also backport this to Odoo 16 then?

**Comment by CRogos** [comment]
@pedrobaeza  could you merge this PR and the v16 backport https://github.com/OCA/project/pull/1339? 
Thank you.

**Pull request merged**
