### PR TITLE
[ADD] add new module: business_requirement

### PR DESCRIPTION
**Pull request by martintorresvm**
Changes to be committed:
    new file:   business_requirement/README.rst#
    new file:   business_requirement/**init**.py
    new file:   business_requirement/**openerp**.py
    new file:   business_requirement/data/business_data.xml
    new file:   business_requirement/data/business_sequence.xml
    new file:   business_requirement/models/**init**.py
    new file:   business_requirement/models/business.py
    new file:   business_requirement/security/ir.model.access.csv
    new file:   business_requirement/security/security.xml
    new file:   business_requirement/static/description/icon.png
    new file:   business_requirement/static/img/bus_req.png
    new file:   business_requirement/static/img/bus_req_alias.png
    new file:   business_requirement/static/img/bus_req_approved.png
    new file:   business_requirement/static/img/bus_req_cancel.png
    new file:   business_requirement/static/img/bus_req_confirmed.png
    new file:   business_requirement/static/img/bus_req_cust_story.png
    new file:   business_requirement/static/img/bus_req_done.png
    new file:   business_requirement/static/img/bus_req_drop.png
    new file:   business_requirement/static/img/bus_req_module_diag.png
    new file:   business_requirement/static/img/bus_req_tags.png
    new file:   business_requirement/static/img/bus_req_tags2.png
    new file:   business_requirement/static/img/bus_req_tree.png
    new file:   business_requirement/static/img/module_diag.graphml
    new file:   business_requirement/tests/**init**.py#
    new file:   business_requirement/tests/test_br.py
    new file:   business_requirement/views/business_viw.xml
    new file:   business_requirement/wizards/**init**.py
    new file:   business_requirement/wizards/mail_compose_message.py

### CODE REVIEW

**Comment by martintorresvm** [comment]
This is the new PR which replaces the old one: #127

**Comment by elicoidal** [comment]
:+1: 
@dreispt @jbeficent @pedrobaeza @jgrandguillaume 
We have cleansed a lot this code based on our usage in the last few month.
We tried to keep all original remarks and discussions since the origin and I think that they should be ready for review and merge.
There are multiple module and this one is the base one: we will add one PR per module.
Honestly, I think it would be better to have a specific repo for the concept as we have already about 10 related modules.

**Comment by dreispt** [comment]
@elicoidal IMO the topic is different enough to deserve a repo. If we have critical mass for it, sounds good to me.
I can open a discussion about it on the Contributors ML.

**Comment by elicoidal** [comment]
@dreispt thanks for the feedback.
We have about 10 modules ready and @jbeficent have potential another 3 or 4 based on change requests, parenting management, maybe earned value etc.
A discussion was started some months ago: I can refresh it with a ping and news on the topic

**Comment by elicoidal** [comment]
#127

**Comment by dreispt** [comment]
I feel that earned value is Project Management and should go here. Change Management too.
Business analysis can sit on top of those feature for an additional layer, adding the detail at the level of requirements/features.

I don't recall the previous discussion right now, you are welcome to revive it.

**Comment by elicoidal** [comment]
Agree: we will need link modules between them.
Just resent a communication in the community.

**Comment by elicoidal** [comment]
@victormartinelicocorp Can you make sure to deprecate completely api.one?
@pedrobaeza there are some error due to rst enumerated list in ci but I am not sure this is important. Not sure either how to fix it (in long list the enumerated list are usually restarted at 1.)

**Comment by elicoidal** [comment]
besides @victormartinelicocorp  please check:

> business_requirement/**init**.py:1: [W7902(duplicate-xml-record-id), ] Duplicate xml record id business_requirement.seq_business_requirement.noupdate=1
> business_requirement/**init**.py:1: [W7902(duplicate-xml-record-id), ] Duplicate xml record id business_requirement.seq_type_business_requirement.noupdate=1

**Comment by blaggacao** [comment]
@elicoidal @victormartinelicocorp  Nice! Roughly, what would be the task (areas) to make this v9?

**Comment by elicoidal** [comment]
@blaggacao IMO not much as this is new API.
More is expect for the module business_requirement_project because in v9 projects are not parent/child anymore so this ideally (but not mandatory should be implemented).
Besides there might be many small modifications in the project fields between 8 and 9: I dont think this is so difficult though.
Same would happen with business_requirement_crm: some fields in SQ might have evolved.
Last but not least we rely on pricelists for the estimations: it is possible that that part requires some tweaking.

**Comment by martintorresvm** [comment]
@elicoidal As I show you Travis Fails on this point but IMO should not. Could you check what is wrong with my `rst` file?:

Start lint check just in modules changed

************\* Module business_requirement
business_requirement/**init**.py:1: [E7901(rst-syntax-error), ] README.rst:7 Enumerated list start value not ordinal-1: "2" (ordinal 2)
business_requirement/**init**.py:1: [E7901(rst-syntax-error), ] README.rst:7 Enumerated list start value not ordinal-1: "3" (ordinal 3)
business_requirement/**init**.py:1: [E7901(rst-syntax-error), ] README.rst:7 Enumerated list start value not ordinal-1: "4" (ordinal 4)
business_requirement/**init**.py:1: [E7901(rst-syntax-error), ] README.rst:7 Enumerated list start value not ordinal-1: "5" (ordinal 5)
business_requirement/**init**.py:1: [E7901(rst-syntax-error), ] README.rst:7 Enumerated list start value not ordinal-1: "6" (ordinal 6)
pylint expected errors 0, found 1!

**Comment by elicoidal** [comment]
@pedrobaeza

**Comment by martintorresvm** [comment]
Wrong repository. I will close this PR and place on https://github.com/OCA/business-requirement/pull/2
@elicoidal?

**Comment by elicoidal** [comment]
replaced by https://github.com/OCA/business-requirement/pull/2

**Pull request closed without merging**
