### PR TITLE
[15.0][MIG] project_wbs

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Having same issues than in the PR for v14. The Buttons in the list  view should not show text. And the button "Create Child WBS Element" gives me an error. Can you apply the same fix?

**Comment by JasminSForgeFlow** [comment]
> Having same issues than in the PR for v14. The Buttons in the list view should not show text. And the button "Create Child WBS Element" gives me an error. Can you apply the same fix?

Fix updated, Thanks

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review :+1:

**Review by JuanyDForgeflow — APPROVED** [review]
Functional Review LGTM!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
