### PR TITLE
[13.0] project_timesheet_time_control : Migration to 13.0

### PR DESCRIPTION
**Pull request by manuelcalerosolis**
This is the migration of project_timesheet_time_control to 13.0

@Tecnativa TT19802

Depends on:
- [x] hr_timesheet_task_stage: OCA/timesheet#319
- [x] hr_timesheet_task_domain: OCA/timesheet#323
- [x] web_ir_actions_act_multi: OCA/web#1533

### CODE REVIEW

**Comment by yajo** [comment]
This is WIP until https://github.com/OCA/timesheet/pull/319 is merged.

**Comment by yajo** [comment]
Could somebody edit the description? I have no permission, and the links are wrong.

**Comment by AntoniRomera** [comment]
@pedrobaeza You can look to update the PR since the last dependency is merged.

**Comment by pedrobaeza** [comment]
@AntoniRomera updated

**Review by pedrobaeza — APPROVED** [review]
Adjusted and tested

**Review by ernestotejeda — APPROVED** [review]

**Pull request merged**
